package suwayomi.tachidesk.server.database

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import suwayomi.tachidesk.manga.model.dataclass.ChapterArchiveState
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionComparisonState
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionSweepItemState
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionSweepKind
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionSweepSessionState
import suwayomi.tachidesk.server.database.migration.M0076_ChapterRevisionSweep
import java.sql.Connection
import java.sql.DriverManager

/**
 * Migration-level guarantees of the sweep and comparison schema.
 *
 * Uses a plain throwaway H2 database and the migration's own SQL, so the assertions describe exactly
 * what the migration creates instead of what the Exposed table objects would create.
 */
class M0076ChapterRevisionSweepTest {
    /**
     * A database that already has the pre-M0076 `chapterrevision` table, and nothing else.
     *
     * Split from [freshDatabase] so a test can insert a revision that predates the comparison
     * dimension and then run the migration over it - exactly what an upgraded server does.
     */
    private fun upgradedDatabase(): Connection =
        DriverManager
            .getConnection("jdbc:h2:mem:chapter_revision_sweep_${System.nanoTime()};DB_CLOSE_DELAY=-1", "sa", "")
            .also { connection ->
                // M0076 only extends chapterrevision, so the columns it references have to exist for
                // this migration to run on its own - exactly as an upgraded database would have them
                connection.createStatement().execute(
                    "CREATE TABLE chapterrevision (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "candidate_key VARCHAR(64) NOT NULL, " +
                        "chapter_key VARCHAR(64) NOT NULL, " +
                        "source_chapter_url VARCHAR(2048) NOT NULL, " +
                        "name VARCHAR(512) NOT NULL, " +
                        "discovered_at BIGINT NOT NULL, " +
                        "updated_at BIGINT NOT NULL, " +
                        "disposition VARCHAR(256) NOT NULL DEFAULT 'CANDIDATE')",
                )
            }

    private fun freshDatabase(): Connection =
        upgradedDatabase().also { connection ->
            connection.createStatement().execute(M0076_ChapterRevisionSweep().sql)
        }

    private fun Connection.session(activeMarker: String?): Int {
        createStatement().execute(
            "INSERT INTO chapterrevisionsweepsession (active_marker, started_at, updated_at) " +
                "VALUES (${activeMarker?.let { "'$it'" } ?: "NULL"}, 1, 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterrevisionsweepsession").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.item(sessionId: Int): Int {
        createStatement().execute(
            "INSERT INTO chapterrevisionsweepitem (session, chapter_key, series_title, chapter_name, " +
                "source_chapter_url, policy, updated_at) " +
                "VALUES ($sessionId, 'chapter-key', 'series', 'chapter', 'https://example.invalid/1', 'AUTO', 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterrevisionsweepitem").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.revision(
        sweepItemId: Int?,
        baselineId: Int?,
        disposition: String = "CANDIDATE",
    ): Int {
        createStatement().execute(
            "INSERT INTO chapterrevision (candidate_key, chapter_key, source_chapter_url, name, discovered_at, " +
                "updated_at, disposition, sweep_item, comparison_baseline_revision) " +
                "VALUES ('${"a".repeat(64)}', 'chapter-key', 'https://example.invalid/1', 'chapter', 1, 1, " +
                "'$disposition', ${sweepItemId ?: "NULL"}, ${baselineId ?: "NULL"})",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterrevision").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    @Test
    fun `creates the three sweep tables`() {
        freshDatabase().use { connection ->
            val names = mutableSetOf<String>()
            connection
                .createStatement()
                .executeQuery("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'PUBLIC'")
                .use { rs ->
                    while (rs.next()) {
                        names += rs.getString(1).uppercase()
                    }
                }

            assertTrue(names.contains("CHAPTERREVISIONSWEEPSESSION"), "session table missing, got $names")
            assertTrue(names.contains("CHAPTERREVISIONSWEEPITEM"), "item table missing, got $names")
            assertTrue(names.contains("CHAPTERREVISIONSWEEPSCHEDULE"), "schedule table missing, got $names")
        }
    }

    @Test
    fun `enforces a single active session and allows unlimited finished ones`() {
        freshDatabase().use { connection ->
            connection.session("ACTIVE")
            // a second non-null marker is refused by the database, not by application code
            assertThrows(Exception::class.java) { connection.session("ACTIVE") }

            // a finished session keeps a null marker, and nulls are distinct in a unique index
            connection.session(null)
            connection.session(null)
        }
    }

    @Test
    fun `items cascade with their session and reject unknown sessions`() {
        freshDatabase().use { connection ->
            val sessionId = connection.session(null)
            connection.item(sessionId)

            assertThrows(Exception::class.java) { connection.item(sessionId + 999) }

            connection.createStatement().execute("DELETE FROM chapterrevisionsweepsession WHERE id = $sessionId")

            val remaining =
                connection
                    .createStatement()
                    .executeQuery("SELECT COUNT(*) FROM chapterrevisionsweepitem WHERE session = $sessionId")
                    .use { rs ->
                        rs.next()
                        rs.getInt(1)
                    }
            assertEquals(0, remaining, "deleting a session must cascade to its items")
        }
    }

    @Test
    fun `session and item defaults describe a fresh run`() {
        freshDatabase().use { connection ->
            val sessionId = connection.session("ACTIVE")
            val itemId = connection.item(sessionId)

            connection.createStatement().executeQuery("SELECT * FROM chapterrevisionsweepsession WHERE id = $sessionId").use { rs ->
                assertTrue(rs.next())
                assertEquals(ChapterRevisionSweepSessionState.RUNNING.name, rs.getString("state"))
                assertEquals(ChapterRevisionSweepKind.MANUAL_RECENT.name, rs.getString("kind"))
                // null means the whole history was selected, which is what a full sweep records
                assertNull(rs.getObject("newest_per_series"))
                assertEquals(2L, rs.getLong("item_delay_seconds"))
                assertEquals(300L, rs.getLong("retry_seconds"))
                assertEquals(3, rs.getInt("max_attempts"))
                assertNull(rs.getObject("next_item_at"))
                assertNull(rs.getObject("finished_at"))
            }

            connection.createStatement().executeQuery("SELECT * FROM chapterrevisionsweepitem WHERE id = $itemId").use { rs ->
                assertTrue(rs.next())
                assertEquals(ChapterRevisionSweepItemState.PENDING.name, rs.getString("state"))
                assertEquals(0, rs.getInt("attempts"))
                assertNull(rs.getObject("last_error"))
                assertNull(rs.getObject("candidate_count"))
                assertNull(rs.getObject("due_at"))
            }
        }
    }

    @Test
    fun `comparison columns start unevaluated and a pruned baseline is nulled instead of cascading`() {
        freshDatabase().use { connection ->
            val baselineId = connection.revision(null, null)
            val comparedId = connection.revision(null, baselineId)

            connection.createStatement().executeQuery("SELECT * FROM chapterrevision WHERE id = $baselineId").use { rs ->
                assertTrue(rs.next())
                // a row the migration never classified was never compared: saying PENDING would claim a
                // comparison that no run owes
                assertEquals(ChapterRevisionComparisonState.NOT_EVALUATED.name, rs.getString("comparison_state"))
                assertNull(rs.getObject("comparison_baseline_revision"))
                assertNull(rs.getObject("compared_at"))
                assertNull(rs.getObject("comparison_error"))
                assertNull(rs.getObject("comparison_cleanup_due_at"))
                assertNull(rs.getObject("sweep_item"))
            }

            // the audit of the comparison survives the removal of the revision it was decided against
            connection.createStatement().execute("DELETE FROM chapterrevision WHERE id = $baselineId")

            connection
                .createStatement()
                .executeQuery(
                    "SELECT comparison_baseline_revision FROM chapterrevision WHERE id = $comparedId",
                ).use { rs ->
                    assertTrue(rs.next())
                    assertNull(rs.getObject("comparison_baseline_revision"))
                }
        }
    }

    @Test
    fun `a revision that predates the comparison dimension is never evaluated`() {
        upgradedDatabase().use { connection ->
            // the row exists before the dimension does, so only the migration can classify it
            connection.createStatement().execute(
                "INSERT INTO chapterrevision (candidate_key, chapter_key, source_chapter_url, name, " +
                    "discovered_at, updated_at) " +
                    "VALUES ('${"b".repeat(64)}', 'chapter-key', 'https://example.invalid/2', 'chapter', 1, 1)",
            )

            connection.createStatement().execute(M0076_ChapterRevisionSweep().sql)

            connection.createStatement().executeQuery("SELECT comparison_state FROM chapterrevision").use { rs ->
                assertTrue(rs.next())
                assertEquals(ChapterRevisionComparisonState.NOT_EVALUATED.name, rs.getString("comparison_state"))
            }
        }
    }

    @Test
    fun `a sweep item owns at most one revision and unrelated revisions keep a null binding`() {
        freshDatabase().use { connection ->
            val sessionId = connection.session(null)
            val itemId = connection.item(sessionId)

            connection.revision(itemId, null)
            connection.revision(null, null)
            connection.revision(null, null)

            // one candidate per item: retrying an item can never record a second revision
            assertThrows(Exception::class.java) { connection.revision(itemId, null) }

            connection.createStatement().executeQuery("SELECT COUNT(*) FROM chapterrevision WHERE sweep_item IS NULL").use { rs ->
                assertTrue(rs.next())
                // both dialects treat nulls as distinct in a unique index
                assertEquals(2, rs.getInt(1))
            }
        }
    }

    @Test
    fun `deleting a sweep item releases its revision without deleting it`() {
        freshDatabase().use { connection ->
            val sessionId = connection.session(null)
            val itemId = connection.item(sessionId)
            val revisionId = connection.revision(itemId, null)

            connection.createStatement().execute("DELETE FROM chapterrevisionsweepitem WHERE id = $itemId")

            connection.createStatement().executeQuery("SELECT sweep_item FROM chapterrevision WHERE id = $revisionId").use { rs ->
                assertTrue(rs.next())
                assertNull(rs.getObject("sweep_item"), "a sweep is an audit: the content it discovered is kept")
            }
        }
    }

    @Test
    fun `the schedule is a singleton`() {
        freshDatabase().use { connection ->
            connection.createStatement().execute(
                "INSERT INTO chapterrevisionsweepschedule (id, next_due_at, updated_at) VALUES (1, 1000, 1)",
            )

            // a schedule that never failed a start has no retry pending
            connection.createStatement().executeQuery("SELECT retry_not_before FROM chapterrevisionsweepschedule").use { rs ->
                assertTrue(rs.next())
                assertNull(rs.getObject("retry_not_before"))
            }

            // a second schedule row is impossible in the database, so a restart can never invent one
            assertThrows(Exception::class.java) {
                connection.createStatement().execute(
                    "INSERT INTO chapterrevisionsweepschedule (id, next_due_at, updated_at) VALUES (2, 1000, 1)",
                )
            }

            connection.createStatement().executeQuery("SELECT COUNT(*) FROM chapterrevisionsweepschedule").use { rs ->
                assertTrue(rs.next())
                assertEquals(1, rs.getInt(1))
            }
        }
    }

    @Test
    fun `creates the unique, claim and backlog indexes`() {
        freshDatabase().use { connection ->
            val indexedColumnSets = mutableListOf<Set<String>>()

            connection
                .createStatement()
                .executeQuery(
                    "SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.INDEX_COLUMNS " +
                        "WHERE TABLE_NAME IN ('CHAPTERREVISIONSWEEPSESSION', 'CHAPTERREVISIONSWEEPITEM', 'CHAPTERREVISION') " +
                        "ORDER BY TABLE_NAME, INDEX_NAME, ORDINAL_POSITION",
                ).use { rs ->
                    val columnsByIndex = linkedMapOf<String, MutableSet<String>>()
                    while (rs.next()) {
                        val key = rs.getString("TABLE_NAME") + "." + rs.getString("INDEX_NAME")
                        columnsByIndex.getOrPut(key) { linkedSetOf() }.add(rs.getString("COLUMN_NAME").uppercase())
                    }
                    indexedColumnSets += columnsByIndex.values
                }

            // the single-owner invariants and the two real query paths
            assertTrue(indexedColumnSets.contains(setOf("ACTIVE_MARKER")))
            assertTrue(indexedColumnSets.contains(setOf("STATE", "NEXT_ITEM_AT", "ID")))
            assertTrue(indexedColumnSets.contains(setOf("SESSION", "STATE", "DUE_AT", "ID")))
            assertTrue(indexedColumnSets.contains(setOf("SESSION", "ID")))
            // one candidate per sweep item, and the comparison audit browsed per state
            assertTrue(indexedColumnSets.contains(setOf("SWEEP_ITEM")))
            assertTrue(indexedColumnSets.contains(setOf("COMPARISON_STATE", "ID")))
            // the unchanged-payload cleanup is claimed by its persisted due time
            assertTrue(indexedColumnSets.contains(setOf("COMPARISON_CLEANUP_DUE_AT", "ID")))
        }
    }

    @Test
    fun `the migration sql is portable across both supported dialects`() {
        val sql = M0076_ChapterRevisionSweep().sql

        // the identity syntax both H2 and PostgreSQL accept, used by every created table
        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"))
        // constructs only one of the two dialects would accept
        listOf("AUTO_INCREMENT", "SERIAL", "IDENTITY(", "ENGINE=", "UNSIGNED", "IF EXISTS").forEach { dialectSpecific ->
            assertFalse(sql.contains(dialectSpecific), "migration must not use $dialectSpecific")
        }
        // every column the runtime table objects map is really created, so a downgrade cannot silently
        // drop one of them
        listOf(
            "comparison_state",
            "comparison_baseline_revision",
            "compared_at",
            "comparison_error",
            "comparison_cleanup_due_at",
            "sweep_item",
            "retry_not_before",
        ).forEach { column -> assertTrue(sql.contains(column), "missing column $column") }

        // the archive state column is referenced by the migrations that created it, never re-created here
        assertTrue(sql.startsWith("CREATE TABLE"))
        assertNotNull(ChapterArchiveState.values().firstOrNull())
    }
}
