package suwayomi.tachidesk.server.database

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import org.jetbrains.exposed.v1.jdbc.Database
import org.jetbrains.exposed.v1.jdbc.JdbcTransaction
import org.jetbrains.exposed.v1.jdbc.transactions.TransactionManager
import org.jetbrains.exposed.v1.jdbc.transactions.transaction
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import suwayomi.tachidesk.manga.model.dataclass.BackupRestoreHandoffState
import suwayomi.tachidesk.manga.model.dataclass.BackupRestoreJobState
import suwayomi.tachidesk.manga.model.dataclass.BackupRestorePhase
import suwayomi.tachidesk.server.database.migration.M0075_BackupRestoreJob
import suwayomi.tachidesk.test.ApplicationTest
import java.util.UUID

class M0075BackupRestoreJobTest : ApplicationTest() {
    private lateinit var database: Database

    @BeforeEach
    fun setUp() {
        val defaultDatabase = TransactionManager.defaultDatabase
        database = Database.connect("jdbc:h2:mem:backuprestorejob-${UUID.randomUUID()};DB_CLOSE_DELAY=-1", "org.h2.Driver")
        TransactionManager.defaultDatabase = defaultDatabase
        transaction(database) {
            // M0074 creates the bootstrap session; M0075 only extends it, so the part it extends has to
            // exist for this migration to run on its own
            exec("CREATE TABLE archivebootstrapsession (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)")
            M0075_BackupRestoreJob().run()
        }
    }

    private fun JdbcTransaction.insertJob(restoreId: String) {
        exec(
            "INSERT INTO backuprestorejob (restore_id, staged_relative_path, staged_size, staged_sha256, flags, created_at, updated_at) " +
                "VALUES ('$restoreId', '$restoreId.tachibk', 4096, '${"a".repeat(64)}', '1111111', 1, 1)",
        )
    }

    private fun JdbcTransaction.jobIdOf(restoreId: String): Int =
        exec("SELECT id FROM backuprestorejob WHERE restore_id = '$restoreId'") {
            assertTrue(it.next())
            it.getInt("id")
        }!!

    private fun JdbcTransaction.insertAudit(
        jobId: Int,
        auditKey: String,
    ) {
        exec(
            "INSERT INTO backuprestorejobaudit (job, level, phase, manga_index, source_id, source_name, message, audit_key, created_at) " +
                "VALUES ($jobId, 'MANGA_ERROR', '${BackupRestorePhase.MANGA.name}', 3, NULL, NULL, 'series failed', '$auditKey', 1)",
        )
    }

    @Test
    fun `defaults a new job to queued and keeps the payload pointers`() {
        transaction(database) {
            insertJob("job-defaults")

            exec(
                "SELECT state, phase, category_mapping, manga_index, manga_count, error_count, handoff_state, " +
                    "handoff_category_overrides, handoff_session_id, staged_deleted_at, last_error, " +
                    "staged_relative_path, staged_size, staged_sha256 FROM backuprestorejob",
            ) {
                assertTrue(it.next())
                assertEquals(BackupRestoreJobState.QUEUED.name, it.getString("state"))
                assertEquals(BackupRestorePhase.PENDING.name, it.getString("phase"))
                assertEquals("", it.getString("category_mapping"))
                assertEquals(0, it.getInt("manga_index"))
                assertEquals(0, it.getInt("manga_count"))
                assertEquals(0, it.getInt("error_count"))
                assertEquals(BackupRestoreHandoffState.NONE.name, it.getString("handoff_state"))
                assertEquals("", it.getString("handoff_category_overrides"))
                assertNull(it.getObject("handoff_session_id"))
                assertNull(it.getObject("staged_deleted_at"))
                assertNull(it.getString("last_error"))
                assertEquals("job-defaults.tachibk", it.getString("staged_relative_path"))
                assertEquals(4096L, it.getLong("staged_size"))
                assertEquals("a".repeat(64), it.getString("staged_sha256"))
            }
        }
    }

    @Test
    fun `rejects a second job with the same restore id`() {
        transaction(database) {
            insertJob("job-unique")

            val failure = runCatching { insertJob("job-unique") }.exceptionOrNull()
            assertNotNull(failure)

            exec("SELECT COUNT(*) AS total FROM backuprestorejob") {
                assertTrue(it.next())
                assertEquals(1, it.getInt("total"))
            }
        }
    }

    @Test
    fun `cascades audit rows when their job is deleted`() {
        transaction(database) {
            insertJob("job-cascade")
            val jobId = jobIdOf("job-cascade")

            exec(
                "INSERT INTO backuprestorejobaudit (job, level, phase, manga_index, source_id, source_name, " +
                    "message, audit_key, created_at) " +
                    "VALUES ($jobId, 'MANGA_ERROR', '${BackupRestorePhase.MANGA.name}', 3, NULL, NULL, 'series failed', 'MANGA:3', 1), " +
                    "($jobId, 'MISSING_SOURCE', '${BackupRestorePhase.PENDING.name}', NULL, 42, 'Missing source', " +
                    "'source is not installed', 'SOURCE:42', 1)",
            )

            exec("DELETE FROM backuprestorejob WHERE id = $jobId")

            exec("SELECT COUNT(*) AS total FROM backuprestorejobaudit") {
                assertTrue(it.next())
                assertEquals(0, it.getInt("total"))
            }
        }
    }

    @Test
    fun `allows one report per audit key per job so re-recording cannot duplicate it`() {
        transaction(database) {
            insertJob("job-audit-key")
            insertJob("job-audit-other")
            val jobId = jobIdOf("job-audit-key")
            val otherJobId = jobIdOf("job-audit-other")

            insertAudit(jobId, "MANGA:3")
            val duplicate = runCatching { insertAudit(jobId, "MANGA:3") }.exceptionOrNull()
            assertNotNull(duplicate)

            // the same key under another job is a different report, which is what makes the key a
            // per-job identity rather than a global one
            insertAudit(otherJobId, "MANGA:3")

            exec("SELECT COUNT(*) AS total FROM backuprestorejobaudit") {
                assertTrue(it.next())
                assertEquals(2, it.getInt("total"))
            }
        }
    }

    @Test
    fun `keeps the bootstrap session origin unique and nullable`() {
        transaction(database) {
            exec(
                "INSERT INTO archivebootstrapsession (origin_key) VALUES ('restore-a'), (NULL), (NULL)",
            )
            val duplicate =
                runCatching {
                    exec("INSERT INTO archivebootstrapsession (origin_key) VALUES ('restore-a')")
                }.exceptionOrNull()
            assertNotNull(duplicate)

            exec("SELECT COUNT(*) AS total FROM archivebootstrapsession WHERE origin_key IS NULL") {
                assertTrue(it.next())
                // a directly started run has no origin, and two of them may coexist as far as the schema
                // is concerned; what keeps them apart is the active marker, not this index
                assertEquals(2, it.getInt("total"))
            }
        }
    }

    @Test
    fun `creates the unique, claim, audit and origin indexes`() {
        transaction(database) {
            val indexedColumnSets = mutableListOf<Set<String>>()

            exec(
                "SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.INDEX_COLUMNS " +
                    "WHERE TABLE_NAME IN ('BACKUPRESTOREJOB', 'BACKUPRESTOREJOBAUDIT', 'ARCHIVEBOOTSTRAPSESSION') " +
                    "ORDER BY TABLE_NAME, INDEX_NAME, ORDINAL_POSITION",
            ) {
                val columnsByIndex = linkedMapOf<String, MutableSet<String>>()
                while (it.next()) {
                    val key = it.getString("TABLE_NAME") + "." + it.getString("INDEX_NAME")
                    columnsByIndex.getOrPut(key) { linkedSetOf() }.add(it.getString("COLUMN_NAME").uppercase())
                }
                indexedColumnSets += columnsByIndex.values
            }

            assertTrue(indexedColumnSets.contains(setOf("RESTORE_ID")))
            assertTrue(indexedColumnSets.contains(setOf("STATE", "ID")))
            assertTrue(indexedColumnSets.contains(setOf("JOB", "ID")))
            assertTrue(indexedColumnSets.contains(setOf("JOB", "AUDIT_KEY")))
            assertTrue(indexedColumnSets.contains(setOf("ORIGIN_KEY")))
        }
    }
}
