package suwayomi.tachidesk.server.database

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import suwayomi.tachidesk.manga.model.dataclass.ChapterIntegrityAuditItemState
import suwayomi.tachidesk.manga.model.dataclass.ChapterIntegrityAuditSessionState
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionIntegrityState
import suwayomi.tachidesk.server.database.migration.M0079_ChapterRevisionIntegrityAudit
import java.sql.Connection
import java.sql.DriverManager

/**
 * Migration-level guarantees of the archive integrity audit and the rollback record.
 *
 * Uses a plain throwaway H2 database and the migration's own SQL, so what is asserted is exactly what
 * the migration creates rather than what the Exposed table objects would create.
 */
class M0079ChapterRevisionIntegrityAuditTest {
    /**
     * A database that already has `chapterrevision` before M0079, and nothing else.
     *
     * Split from [freshDatabase] so a revision that existed before the audit dimension did can be
     * inserted and then migrated over, which is exactly what an upgraded server does.
     */
    private fun upgradedDatabase(): Connection =
        DriverManager
            .getConnection("jdbc:h2:mem:integrity_audit_${System.nanoTime()};DB_CLOSE_DELAY=-1", "sa", "")
            .also { connection ->
                connection.createStatement().execute(
                    "CREATE TABLE chapterrevision (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "candidate_key VARCHAR(64) NOT NULL, " +
                        "chapter_key VARCHAR(64) NOT NULL, " +
                        "source_chapter_url VARCHAR(2048) NOT NULL, " +
                        "name VARCHAR(512) NOT NULL, " +
                        "discovered_at BIGINT NOT NULL, " +
                        "updated_at BIGINT NOT NULL)",
                )
            }

    private fun freshDatabase(): Connection =
        upgradedDatabase().also { connection ->
            connection.createStatement().execute(M0079_ChapterRevisionIntegrityAudit().sql)
        }

    private fun Connection.revision(
        candidateKey: String = "a".repeat(64),
        chapterKey: String = "c".repeat(64),
    ): Int {
        createStatement().execute(
            "INSERT INTO chapterrevision (candidate_key, chapter_key, source_chapter_url, name, discovered_at, updated_at) " +
                "VALUES ('$candidateKey', '$chapterKey', 'https://example.invalid/1', 'chapter', 1, 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterrevision").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.session(
        state: String = ChapterIntegrityAuditSessionState.RUNNING.name,
        marker: String? = "ACTIVE",
    ): Int {
        createStatement().execute(
            "INSERT INTO chapterintegrityauditsession (kind, state, active_marker, started_at, updated_at) " +
                "VALUES ('MANUAL_RECENT', '$state', ${marker?.let { "'$it'" } ?: "NULL"}, 1, 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterintegrityauditsession").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.item(
        sessionId: Int,
        revisionId: Int? = null,
    ): Int {
        createStatement().execute(
            "INSERT INTO chapterintegrityaudititem (session, revision, chapter_key, candidate_key, chapter_name, " +
                "cbz_path, cbz_sha256, cbz_size, manifest_path, manifest_sha256, manifest_size, state, attempts, updated_at) " +
                "VALUES ($sessionId, ${revisionId ?: "NULL"}, 'chapter-key', 'candidate-key', 'chapter', " +
                "'revisions/x/x.cbz', '${"a".repeat(64)}', 10, 'revisions/x/x.archive.json', '${"b".repeat(64)}', 20, " +
                "'${ChapterIntegrityAuditItemState.PENDING.name}', 0, 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterintegrityaudititem").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.fails(sql: String): Boolean =
        try {
            createStatement().execute(sql)
            false
        } catch (e: java.sql.SQLException) {
            true
        }

    /**
     * The SQL with its `--` comments removed.
     *
     * A DDL assertion has to read the schema, not the prose that explains it: a `<table> (` followed by
     * a comment line never matches a substring written from the columns alone, which would make the
     * assertion fail for a wording change and pass for a real schema change.
     */
    private fun stripSqlComments(sql: String): String = sql.lines().joinToString("\n") { line -> line.substringBefore("--") }

    private fun Connection.count(table: String): Int =
        createStatement().executeQuery("SELECT COUNT(*) FROM $table").use { rs ->
            rs.next()
            rs.getInt(1)
        }

    private fun Connection.tableNames(): Set<String> =
        mutableSetOf<String>().also { names ->
            createStatement()
                .executeQuery("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'PUBLIC'")
                .use { rs ->
                    while (rs.next()) {
                        names += rs.getString(1).uppercase()
                    }
                }
        }

    private fun Connection.revisionColumns(): Set<String> =
        mutableSetOf<String>().also { names ->
            createStatement()
                .executeQuery("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CHAPTERREVISION'")
                .use { rs ->
                    while (rs.next()) {
                        names += rs.getString(1).lowercase()
                    }
                }
        }

    @Test
    fun `creates the audit tables and the rollback record`() {
        freshDatabase().use { connection ->
            val names = connection.tableNames()

            assertTrue(names.contains("CHAPTERINTEGRITYAUDITSESSION"), "session table missing, got $names")
            assertTrue(names.contains("CHAPTERINTEGRITYAUDITITEM"), "item table missing, got $names")
            assertTrue(names.contains("CHAPTERINTEGRITYAUDITSCHEDULE"), "schedule table missing, got $names")
            assertTrue(names.contains("CHAPTERREVISIONROLLBACK"), "rollback table missing, got $names")
        }
    }

    @Test
    fun `a revision that predates the audit dimension reads as never audited`() {
        upgradedDatabase().use { connection ->
            connection.revision()

            connection.createStatement().execute(M0079_ChapterRevisionIntegrityAudit().sql)

            assertTrue(
                connection.revisionColumns().containsAll(
                    listOf(
                        "integrity_state",
                        "integrity_last_audited_at",
                        "integrity_last_audit_session",
                        "integrity_last_error",
                    ),
                ),
                "the integrity columns are missing",
            )

            connection
                .createStatement()
                .executeQuery("SELECT integrity_state, integrity_last_audited_at FROM chapterrevision")
                .use { rs ->
                    assertTrue(rs.next(), "the pre-existing revision must survive the migration")
                    // nothing is backfilled: nobody ever checked it, so that is what it says
                    assertEquals(ChapterRevisionIntegrityState.NEVER_AUDITED.name, rs.getString(1))
                    rs.getLong(2)
                    assertTrue(rs.wasNull(), "a revision that was never audited has no audit instant")
                }
        }
    }

    @Test
    fun `at most one active audit exists`() {
        freshDatabase().use { connection ->
            connection.session()

            assertTrue(
                connection.fails(
                    "INSERT INTO chapterintegrityauditsession (kind, state, active_marker, started_at, updated_at) " +
                        "VALUES ('MANUAL_FULL', 'PAUSED', 'ACTIVE', 1, 1)",
                ),
                "two active audits must be impossible",
            )

            // nulls are distinct, so any number of terminal runs can keep a null marker
            connection.session(ChapterIntegrityAuditSessionState.COMPLETED.name, marker = null)
            connection.session(ChapterIntegrityAuditSessionState.CANCELLED.name, marker = null)

            assertEquals(3, connection.count("chapterintegrityauditsession"))
        }
    }

    @Test
    fun `an item cascades with its session but never with the revision it names`() {
        freshDatabase().use { connection ->
            val sessionId = connection.session()
            val revisionId = connection.revision()
            connection.item(sessionId, revisionId)

            // the revision column is a plain snapshot, not a foreign key: deleting the row must not
            // erase what the run checked
            connection.createStatement().execute("DELETE FROM chapterrevision WHERE id = $revisionId")
            assertEquals(1, connection.count("chapterintegrityaudititem"), "the item must survive its revision")

            // the session is the only real reference, and it owns its items
            connection.createStatement().execute("DELETE FROM chapterintegrityauditsession WHERE id = $sessionId")
            assertEquals(0, connection.count("chapterintegrityaudititem"), "a run's items cascade with the run")
        }
    }

    @Test
    fun `the schedule is a singleton`() {
        freshDatabase().use { connection ->
            connection.createStatement().execute(
                "INSERT INTO chapterintegrityauditschedule (id, next_due_at, updated_at) VALUES (1, 100, 1)",
            )

            // the id = 1 check, not the primary key alone, is what refuses a different schedule id
            assertTrue(
                connection.fails(
                    "INSERT INTO chapterintegrityauditschedule (id, next_due_at, updated_at) VALUES (2, 100, 1)",
                ),
                "the id = 1 check is what makes a second schedule impossible",
            )
            assertTrue(
                connection.fails(
                    "INSERT INTO chapterintegrityauditschedule (id, next_due_at, updated_at) VALUES (1, 200, 1)",
                ),
                "the single schedule row is never duplicated",
            )
            assertEquals(1, connection.count("chapterintegrityauditschedule"))
        }
    }

    @Test
    fun `a rollback record survives both revisions it names`() {
        freshDatabase().use { connection ->
            val first = connection.revision("d".repeat(64))
            val second = connection.revision("e".repeat(64))

            connection.createStatement().execute(
                "INSERT INTO chapterrevisionrollback (chapter_key, from_revision, to_revision, rolled_back_at) " +
                    "VALUES ('chapter-key', $second, $first, 5)",
            )

            connection.createStatement().execute("DELETE FROM chapterrevision WHERE id IN ($first, $second)")

            connection
                .createStatement()
                .executeQuery("SELECT chapter_key, from_revision, to_revision, rolled_back_at FROM chapterrevisionrollback")
                .use { rs ->
                    assertTrue(rs.next(), "the decision outlives the revisions it names")
                    assertEquals("chapter-key", rs.getString(1))
                    assertEquals(second, rs.getInt(2))
                    assertEquals(first, rs.getInt(3))
                    assertEquals(5, rs.getLong(4))
                }

            // a decision that replaced nothing is still a decision
            connection.createStatement().execute(
                "INSERT INTO chapterrevisionrollback (chapter_key, from_revision, to_revision, rolled_back_at) " +
                    "VALUES ('chapter-key', NULL, NULL, 6)",
            )
            assertEquals(2, connection.count("chapterrevisionrollback"))
        }
    }

    @Test
    fun `the invariants and backlogs are indexes rather than conventions`() {
        freshDatabase().use { connection ->
            val columnsByIndex = linkedMapOf<String, MutableSet<String>>()
            connection
                .createStatement()
                .executeQuery(
                    "SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.INDEX_COLUMNS " +
                        "WHERE TABLE_NAME IN ('CHAPTERINTEGRITYAUDITSESSION', 'CHAPTERINTEGRITYAUDITITEM', " +
                        "'CHAPTERREVISION', 'CHAPTERREVISIONROLLBACK') " +
                        "ORDER BY TABLE_NAME, INDEX_NAME, ORDINAL_POSITION",
                ).use { rs ->
                    while (rs.next()) {
                        val key = rs.getString("TABLE_NAME") + "." + rs.getString("INDEX_NAME")
                        columnsByIndex.getOrPut(key) { linkedSetOf() }.add(rs.getString("COLUMN_NAME").uppercase())
                    }
                }

            val indexed = columnsByIndex.values

            // the unique active marker is the at-most-one-active invariant
            assertTrue(indexed.contains(setOf("ACTIVE_MARKER")))
            // the worker claims the oldest session that may run, and the earliest item of one run
            assertTrue(indexed.contains(setOf("STATE", "NEXT_ITEM_AT", "ID")))
            assertTrue(indexed.contains(setOf("SESSION", "STATE", "DUE_AT", "ID")))
            assertTrue(indexed.contains(setOf("SESSION", "ID")))
            // the findings view pages the integrity dimension per state
            assertTrue(indexed.contains(setOf("INTEGRITY_STATE", "ID")))
            // the rollback history is read globally and per identity, newest first by id
            assertTrue(indexed.contains(setOf("ROLLED_BACK_AT", "ID")))
            assertTrue(indexed.contains(setOf("CHAPTER_KEY", "ROLLED_BACK_AT", "ID")))
        }
    }

    @Test
    fun `the migration sql is portable across both supported dialects`() {
        val sql = M0079_ChapterRevisionIntegrityAudit().sql

        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"))
        listOf("AUTO_INCREMENT", "SERIAL", "IDENTITY(", "ENGINE=", "UNSIGNED").forEach { dialectSpecific ->
            assertFalse(sql.contains(dialectSpecific), "migration must not use $dialectSpecific")
        }

        // every column the runtime table objects map is really created, so a downgrade cannot silently
        // drop one of them
        listOf(
            "kind VARCHAR(64) NOT NULL",
            "state VARCHAR(64) NOT NULL",
            "active_marker VARCHAR(64) NULL",
            "newest_per_manga INT NULL",
            "item_delay_seconds BIGINT NOT NULL",
            "retry_seconds BIGINT NOT NULL",
            "max_attempts INT NOT NULL",
            "next_item_at BIGINT NULL",
            "last_item_at BIGINT NULL",
            "paused_at BIGINT NULL",
            "cancelled_at BIGINT NULL",
            "revision INT NULL",
            "cbz_path VARCHAR(2048) NOT NULL",
            "cbz_sha256 VARCHAR(64) NOT NULL",
            "cbz_size BIGINT NOT NULL",
            "manifest_path VARCHAR(2048) NOT NULL",
            "manifest_sha256 VARCHAR(64) NOT NULL",
            "manifest_size BIGINT NOT NULL",
            "last_error VARCHAR(1024) NULL",
            "due_at BIGINT NULL",
            "retry_not_before BIGINT NULL",
            "from_revision INT NULL",
            "to_revision INT NULL",
            "rolled_back_at BIGINT NOT NULL",
            "integrity_state VARCHAR(64) NOT NULL DEFAULT '${ChapterRevisionIntegrityState.NEVER_AUDITED.name}'",
            "integrity_last_audited_at BIGINT NULL",
            "integrity_last_audit_session INT NULL",
            "integrity_last_error VARCHAR(1024) NULL",
        ).forEach { column -> assertTrue(sql.contains(column), "missing column $column") }

        // the session reference is what keeps an item meaningful, and it may only ever cascade with the
        // run; the revision and the two rollback revisions must stay plain snapshots
        val flattened = stripSqlComments(sql).replace(Regex("\\s+"), " ").trim()
        assertTrue(
            flattened.contains("FOREIGN KEY (session) REFERENCES chapterintegrityauditsession(ID) ON DELETE CASCADE"),
            "an item has to cascade with its run",
        )
        assertFalse(flattened.contains("FOREIGN KEY (revision)"), "the audited revision stays a snapshot")
        assertFalse(flattened.contains("FOREIGN KEY (from_revision)"), "the rollback record stays a snapshot")
        assertFalse(flattened.contains("FOREIGN KEY (to_revision)"), "the rollback record stays a snapshot")

        // the schedule is a singleton by primary key and by an explicit check, not by convention:
        // the primary key alone would still accept any other id
        assertTrue(
            flattened.contains("CREATE TABLE IF NOT EXISTS chapterintegrityauditschedule ( id INT NOT NULL PRIMARY KEY"),
            "the schedule table has to exist with its singleton key, got $flattened",
        )
        assertTrue(
            flattened.contains("CONSTRAINT CHK_CHAPTERINTEGRITYAUDITSCHEDULE_SINGLETON CHECK (id = 1)"),
            "a second schedule row has to be impossible in the database, got $flattened",
        )
    }

    @Test
    fun `no revision is ever marked as audited by the migration itself`() {
        freshDatabase().use { connection ->
            connection.revision()

            val marked =
                connection
                    .createStatement()
                    .executeQuery(
                        "SELECT COUNT(*) FROM chapterrevision WHERE integrity_state <> '${ChapterRevisionIntegrityState.NEVER_AUDITED.name}'",
                    ).use { rs ->
                        rs.next()
                        rs.getInt(1)
                    }

            assertEquals(0, marked, "the migration must not claim any revision was checked")
            assertNotNull(connection.revisionColumns().firstOrNull { it == "integrity_state" })
            assertNull(
                connection
                    .createStatement()
                    .executeQuery("SELECT integrity_last_audit_session FROM chapterrevision")
                    .use { rs ->
                        rs.next()
                        rs.getObject(1)
                    },
            )
        }
    }
}
