package suwayomi.tachidesk.server.database

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionPageAlignmentState
import suwayomi.tachidesk.manga.model.dataclass.ChapterVisualAnalysisState
import suwayomi.tachidesk.server.database.migration.M0077_ChapterRevisionVisualAnalysis
import java.sql.Connection
import java.sql.DriverManager

/**
 * Migration-level guarantees of the visual comparison schema.
 *
 * Uses a plain throwaway H2 database and the migration's own SQL, so the assertions describe exactly
 * what the migration creates instead of what the Exposed table objects would create.
 */
class M0077ChapterRevisionVisualAnalysisTest {
    /**
     * A database that already has the pre-M0077 `chapterrevision` table, and nothing else.
     *
     * Split from [freshDatabase] so a test can insert a revision that predates the visual dimension
     * and then run the migration over it - exactly what an upgraded server does.
     */
    private fun upgradedDatabase(): Connection =
        DriverManager
            .getConnection("jdbc:h2:mem:chapter_revision_visual_${System.nanoTime()};DB_CLOSE_DELAY=-1", "sa", "")
            .also { connection ->
                connection.createStatement().execute(
                    "CREATE TABLE chapterrevision (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "candidate_key VARCHAR(64) NOT NULL, " +
                        "chapter_key VARCHAR(64) NOT NULL, " +
                        "source_chapter_url VARCHAR(2048) NOT NULL, " +
                        "name VARCHAR(512) NOT NULL, " +
                        "discovered_at BIGINT NOT NULL, " +
                        "updated_at BIGINT NOT NULL)",
                )
            }

    private fun freshDatabase(): Connection =
        upgradedDatabase().also { connection ->
            connection.createStatement().execute(M0077_ChapterRevisionVisualAnalysis().sql)
        }

    private fun Connection.revision(candidateKey: String = "a".repeat(64)): Int {
        createStatement().execute(
            "INSERT INTO chapterrevision (candidate_key, chapter_key, source_chapter_url, name, discovered_at, updated_at) " +
                "VALUES ('$candidateKey', 'chapter-key', 'https://example.invalid/1', 'chapter', 1, 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterrevision").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.comparison(
        revisionId: Int,
        baselineId: Int?,
    ): Int {
        createStatement().execute(
            "INSERT INTO chapterrevisioncomparison (revision, baseline_revision, baseline_page_count, " +
                "candidate_page_count, exact_count, visually_equivalent_count, modified_count, added_count, " +
                "removed_count, aligned_count, hamming_threshold, algorithm_version, " +
                "all_pages_visually_equivalent, has_limitations, limitations, created_at, updated_at) " +
                "VALUES ($revisionId, ${baselineId ?: "NULL"}, 2, 2, 1, 0, 1, 0, 0, 2, 2, 'dhash128-v1', " +
                "false, false, NULL, 1, 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM chapterrevisioncomparison").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.page(
        comparisonId: Int,
        revisionId: Int,
        ordinal: Int,
    ) {
        createStatement().execute(
            "INSERT INTO chapterrevisioncomparisonpage (comparison, revision, ordinal, baseline_page_index, " +
                "candidate_page_index, state, hamming_distance, created_at) " +
                "VALUES ($comparisonId, $revisionId, $ordinal, $ordinal, $ordinal, " +
                "'${ChapterRevisionPageAlignmentState.MODIFIED.name}', 9, 1)",
        )
    }

    @Test
    fun `creates the summary and alignment tables`() {
        freshDatabase().use { connection ->
            val names = mutableSetOf<String>()
            connection
                .createStatement()
                .executeQuery("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'PUBLIC'")
                .use { rs ->
                    while (rs.next()) {
                        names += rs.getString(1).uppercase()
                    }
                }

            assertTrue(names.contains("CHAPTERREVISIONCOMPARISON"), "summary table missing, got $names")
            assertTrue(names.contains("CHAPTERREVISIONCOMPARISONPAGE"), "alignment table missing, got $names")
        }
    }

    @Test
    fun `a revision that predates the visual dimension owes no analysis`() {
        upgradedDatabase().use { connection ->
            connection.revision()

            connection.createStatement().execute(M0077_ChapterRevisionVisualAnalysis().sql)

            connection.createStatement().executeQuery("SELECT * FROM chapterrevision").use { rs ->
                assertTrue(rs.next())
                // NOT_REQUIRED, not QUEUED: an upgraded database must not wake up believing it owes
                // thousands of comparisons
                assertEquals(ChapterVisualAnalysisState.NOT_REQUIRED.name, rs.getString("visual_analysis_state"))
                assertEquals(0, rs.getInt("visual_analysis_attempts"))
                assertNull(rs.getObject("visual_analysis_last_error"))
                assertNull(rs.getObject("visual_analysis_last_attempt_at"))
                assertNull(rs.getObject("visual_analysis_next_attempt_at"))
                assertNull(rs.getObject("visual_analysis_completed_at"))
            }
        }
    }

    @Test
    fun `one candidate has at most one summary`() {
        freshDatabase().use { connection ->
            val revisionId = connection.revision()
            connection.comparison(revisionId, null)

            // re-analysing replaces the summary, so a second row for the same candidate is refused
            assertThrows(Exception::class.java) { connection.comparison(revisionId, null) }
        }
    }

    @Test
    fun `removing the baseline nulls the reference instead of deleting the comparison`() {
        freshDatabase().use { connection ->
            val baselineId = connection.revision("b".repeat(64))
            val revisionId = connection.revision("c".repeat(64))
            val comparisonId = connection.comparison(revisionId, baselineId)

            connection.createStatement().execute("DELETE FROM chapterrevision WHERE id = $baselineId")

            connection
                .createStatement()
                .executeQuery("SELECT baseline_revision FROM chapterrevisioncomparison WHERE id = $comparisonId")
                .use { rs ->
                    assertTrue(rs.next(), "the comparison must survive the removal of its baseline")
                    assertNull(rs.getObject("baseline_revision"))
                }
        }
    }

    @Test
    fun `removing the candidate cascades to its summary and alignment`() {
        freshDatabase().use { connection ->
            val revisionId = connection.revision()
            val comparisonId = connection.comparison(revisionId, null)
            connection.page(comparisonId, revisionId, 0)
            connection.page(comparisonId, revisionId, 1)

            connection.createStatement().execute("DELETE FROM chapterrevision WHERE id = $revisionId")

            connection.createStatement().executeQuery("SELECT COUNT(*) FROM chapterrevisioncomparison").use { rs ->
                assertTrue(rs.next())
                assertEquals(0, rs.getInt(1))
            }
            connection.createStatement().executeQuery("SELECT COUNT(*) FROM chapterrevisioncomparisonpage").use { rs ->
                assertTrue(rs.next())
                assertEquals(0, rs.getInt(1))
            }
        }
    }

    @Test
    fun `an alignment ordinal is unique per comparison`() {
        freshDatabase().use { connection ->
            val revisionId = connection.revision()
            val comparisonId = connection.comparison(revisionId, null)
            connection.page(comparisonId, revisionId, 0)

            assertThrows(Exception::class.java) { connection.page(comparisonId, revisionId, 0) }
        }
    }

    @Test
    fun `the alignment row defaults describe a modified page`() {
        freshDatabase().use { connection ->
            val revisionId = connection.revision()
            val comparisonId = connection.comparison(revisionId, null)

            connection.createStatement().execute(
                "INSERT INTO chapterrevisioncomparisonpage (comparison, revision, ordinal, created_at) " +
                    "VALUES ($comparisonId, $revisionId, 0, 1)",
            )

            connection
                .createStatement()
                .executeQuery("SELECT * FROM chapterrevisioncomparisonpage WHERE comparison = $comparisonId")
                .use { rs ->
                    assertTrue(rs.next())
                    assertEquals(ChapterRevisionPageAlignmentState.MODIFIED.name, rs.getString("state"))
                    assertNull(rs.getObject("baseline_page_index"))
                    assertNull(rs.getObject("candidate_page_index"))
                    assertNull(rs.getObject("baseline_thumbnail_relative_path"))
                    assertNull(rs.getObject("baseline_thumbnail_sha256"))
                    assertNull(rs.getObject("baseline_thumbnail_size"))
                    assertNull(rs.getObject("candidate_thumbnail_relative_path"))
                    assertNull(rs.getObject("candidate_thumbnail_sha256"))
                    assertNull(rs.getObject("candidate_thumbnail_size"))
                }
        }
    }

    @Test
    fun `an alignment row keeps a separate preview location for each side`() {
        freshDatabase().use { connection ->
            val revisionId = connection.revision()
            val comparisonId = connection.comparison(revisionId, null)

            // both sides of a rewritten page are reviewed together, so the two locations must be
            // independently storable and independently readable
            connection.createStatement().execute(
                "INSERT INTO chapterrevisioncomparisonpage (comparison, revision, ordinal, state, " +
                    "baseline_thumbnail_relative_path, baseline_thumbnail_sha256, baseline_thumbnail_size, " +
                    "candidate_thumbnail_relative_path, candidate_thumbnail_sha256, candidate_thumbnail_size, " +
                    "created_at) VALUES ($comparisonId, $revisionId, 0, 'MODIFIED', " +
                    "'revision-comparisons/aaaa/1-1/000000-baseline.jpg', 'aaaaaaaa', 10, " +
                    "'revision-comparisons/aaaa/1-1/000000-candidate.jpg', 'bbbbbbbb', 20, 1)",
            )

            connection
                .createStatement()
                .executeQuery("SELECT * FROM chapterrevisioncomparisonpage WHERE comparison = $comparisonId")
                .use { rs ->
                    assertTrue(rs.next())
                    assertEquals(
                        "revision-comparisons/aaaa/1-1/000000-baseline.jpg",
                        rs.getString("baseline_thumbnail_relative_path"),
                    )
                    assertEquals(10L, rs.getLong("baseline_thumbnail_size"))
                    assertEquals(
                        "revision-comparisons/aaaa/1-1/000000-candidate.jpg",
                        rs.getString("candidate_thumbnail_relative_path"),
                    )
                    assertEquals(20L, rs.getLong("candidate_thumbnail_size"))
                }

            // one side may have a preview while the other does not: an added row only has a candidate,
            // a removed row only a baseline
            connection.createStatement().execute(
                "INSERT INTO chapterrevisioncomparisonpage (comparison, revision, ordinal, state, " +
                    "candidate_thumbnail_relative_path, candidate_thumbnail_sha256, candidate_thumbnail_size, " +
                    "created_at) VALUES ($comparisonId, $revisionId, 1, 'ADDED', 'candidate.jpg', 'cccc', 30, 1)",
            )

            connection
                .createStatement()
                .executeQuery("SELECT * FROM chapterrevisioncomparisonpage WHERE comparison = $comparisonId AND ordinal = 1")
                .use { rs ->
                    assertTrue(rs.next())
                    assertNull(rs.getObject("baseline_thumbnail_relative_path"))
                    assertNull(rs.getObject("baseline_thumbnail_size"))
                    assertNotNull(rs.getString("candidate_thumbnail_relative_path"))
                }
        }
    }

    @Test
    fun `a failed analysis records a category beside its message`() {
        freshDatabase().use { connection ->
            val revisionId = connection.revision()
            connection.createStatement().execute(
                "UPDATE chapterrevision SET visual_analysis_state = 'FAILED', " +
                    "visual_analysis_last_error = 'the archived baseline pages are not available', " +
                    "visual_analysis_last_failure = 'BASELINE_MISSING' WHERE id = $revisionId",
            )

            connection
                .createStatement()
                .executeQuery("SELECT * FROM chapterrevision WHERE id = $revisionId")
                .use { rs ->
                    assertTrue(rs.next())
                    assertEquals(ChapterVisualAnalysisState.FAILED.name, rs.getString("visual_analysis_state"))
                    assertEquals("BASELINE_MISSING", rs.getString("visual_analysis_last_failure"))
                }
        }
    }

    @Test
    fun `creates the claim and ordering indexes`() {
        freshDatabase().use { connection ->
            val indexedColumnSets = mutableListOf<Set<String>>()

            connection
                .createStatement()
                .executeQuery(
                    "SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.INDEX_COLUMNS " +
                        "WHERE TABLE_NAME IN ('CHAPTERREVISION', 'CHAPTERREVISIONCOMPARISON', " +
                        "'CHAPTERREVISIONCOMPARISONPAGE') ORDER BY TABLE_NAME, INDEX_NAME, ORDINAL_POSITION",
                ).use { rs ->
                    val columnsByIndex = linkedMapOf<String, MutableSet<String>>()
                    while (rs.next()) {
                        val key = rs.getString("TABLE_NAME") + "." + rs.getString("INDEX_NAME")
                        columnsByIndex.getOrPut(key) { linkedSetOf() }.add(rs.getString("COLUMN_NAME").uppercase())
                    }
                    indexedColumnSets += columnsByIndex.values
                }

            // the worker claims by state and orders by the persisted due time
            assertTrue(indexedColumnSets.contains(setOf("VISUAL_ANALYSIS_STATE", "VISUAL_ANALYSIS_NEXT_ATTEMPT_AT", "ID")))
            // one summary per candidate, and an alignment read strictly in order
            assertTrue(indexedColumnSets.contains(setOf("REVISION")))
            assertTrue(indexedColumnSets.contains(setOf("COMPARISON", "ORDINAL")))
            // the review UI pages a candidate's alignment and filters it by state
            assertTrue(indexedColumnSets.contains(setOf("REVISION", "STATE", "ORDINAL")))
        }
    }

    @Test
    fun `the migration sql is portable across both supported dialects`() {
        val sql = M0077_ChapterRevisionVisualAnalysis().sql

        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"))
        listOf("AUTO_INCREMENT", "SERIAL", "IDENTITY(", "ENGINE=", "UNSIGNED", "IF EXISTS").forEach { dialectSpecific ->
            assertFalse(sql.contains(dialectSpecific), "migration must not use $dialectSpecific")
        }
        listOf(
            "visual_analysis_state",
            "visual_analysis_attempts",
            "visual_analysis_last_error",
            "visual_analysis_last_failure",
            "visual_analysis_last_attempt_at",
            "visual_analysis_next_attempt_at",
            "visual_analysis_completed_at",
            "chapterrevisioncomparison",
            "chapterrevisioncomparisonpage",
            "baseline_thumbnail_relative_path",
            "baseline_thumbnail_sha256",
            "baseline_thumbnail_size",
            "candidate_thumbnail_relative_path",
            "candidate_thumbnail_sha256",
            "candidate_thumbnail_size",
            "algorithm_version",
            "hamming_threshold",
        ).forEach { fragment -> assertTrue(sql.contains(fragment), "missing $fragment") }

        // a local thumbnail location is recorded but never written into the API surface, so the
        // migration is the only place it is named
        assertTrue(sql.contains("baseline_revision"))
        // the single-thumbnail columns were replaced, not kept beside the per-side ones; the leading
        // space is what keeps these from matching inside "baseline_thumbnail_relative_path"
        assertFalse(sql.contains(" thumbnail_relative_path VARCHAR"))
        assertFalse(sql.contains(" thumbnail_sha256 VARCHAR"))
    }
}
