package suwayomi.tachidesk.server.database

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import suwayomi.tachidesk.manga.model.dataclass.CanonicalBindingRole
import suwayomi.tachidesk.manga.model.dataclass.CanonicalDuplicateStrategy
import suwayomi.tachidesk.server.database.migration.M0078_CanonicalIdentity
import java.sql.Connection
import java.sql.DriverManager

/**
 * Migration-level guarantees of the canonical identity control plane.
 *
 * Uses a plain throwaway H2 database and the migration's own SQL, so what is asserted is exactly what
 * the migration creates rather than what the Exposed table objects would create.
 */
class M0078CanonicalIdentityTest {
    /**
     * A database that already has `manga` and the pre-M0078 `chapterrevision`, and nothing else.
     *
     * Split from [freshDatabase] so a revision that predates canonical identity can be inserted and
     * then migrated over, which is exactly what an upgraded server does.
     */
    private fun upgradedDatabase(): Connection =
        DriverManager
            .getConnection("jdbc:h2:mem:canonical_identity_${System.nanoTime()};DB_CLOSE_DELAY=-1", "sa", "")
            .also { connection ->
                connection.createStatement().execute(
                    "CREATE TABLE manga (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "url VARCHAR(2048) NOT NULL, title VARCHAR(512) NOT NULL)",
                )
                connection.createStatement().execute(
                    "CREATE TABLE chapterrevision (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "candidate_key VARCHAR(64) NOT NULL, " +
                        "chapter_key VARCHAR(64) NOT NULL, " +
                        "source_chapter_url VARCHAR(2048) NOT NULL, " +
                        "name VARCHAR(512) NOT NULL, " +
                        "discovered_at BIGINT NOT NULL, " +
                        "updated_at BIGINT NOT NULL)",
                )
            }

    private fun freshDatabase(): Connection =
        upgradedDatabase().also { connection ->
            connection.createStatement().execute(M0078_CanonicalIdentity().sql)
        }

    private fun Connection.manga(title: String = "series"): Int {
        createStatement().execute("INSERT INTO manga (url, title) VALUES ('$title', '$title')")
        return createStatement().executeQuery("SELECT MAX(id) FROM manga").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.work(
        workKey: String = "work-key",
        title: String = "Series",
    ): Int {
        createStatement().execute(
            "INSERT INTO canonicalwork (work_key, title, duplicate_strategy, created_at, updated_at) " +
                "VALUES ('$workKey', '$title', '${CanonicalDuplicateStrategy.KEEP_ALL.name}', 1, 1)",
        )
        return createStatement().executeQuery("SELECT MAX(id) FROM canonicalwork").use { rs ->
            rs.next()
            rs.getInt(1)
        }
    }

    private fun Connection.binding(
        workId: Int,
        mangaId: Int?,
        priority: Int = 0,
        primaryMarker: String? = null,
        snapshot: String? = "snapshot-title",
    ) {
        createStatement().execute(
            "INSERT INTO canonicalsourcebinding (work, manga, role, priority, primary_marker, manga_title, " +
                "manga_url, source_id, source_name, bound_at, updated_at) VALUES (" +
                "$workId, ${mangaId ?: "NULL"}, '${CanonicalBindingRole.ACTIVE.name}', $priority, " +
                "${primaryMarker?.let { "'$it'" } ?: "NULL"}, " +
                "${snapshot?.let { "'$it'" } ?: "NULL"}, NULL, 7, 'source', 1, 1)",
        )
    }

    private fun Connection.fails(sql: String): Boolean =
        try {
            createStatement().execute(sql)
            false
        } catch (e: java.sql.SQLException) {
            true
        }

    private fun Connection.tableNames(): Set<String> =
        mutableSetOf<String>().also { names ->
            createStatement()
                .executeQuery("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'PUBLIC'")
                .use { rs ->
                    while (rs.next()) {
                        names += rs.getString(1).uppercase()
                    }
                }
        }

    private fun Connection.revisionColumns(): Set<String> =
        mutableSetOf<String>().also { names ->
            createStatement()
                .executeQuery("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CHAPTERREVISION'")
                .use { rs ->
                    while (rs.next()) {
                        names += rs.getString(1).lowercase()
                    }
                }
        }

    @Test
    fun `creates the canonical work and binding tables`() {
        freshDatabase().use { connection ->
            val names = connection.tableNames()

            assertTrue(names.contains("CANONICALWORK"), "work table missing, got $names")
            assertTrue(names.contains("CANONICALSOURCEBINDING"), "binding table missing, got $names")
        }
    }

    @Test
    fun `a revision that predates canonical identity stays unbound`() {
        upgradedDatabase().use { connection ->
            connection.createStatement().execute(
                "INSERT INTO chapterrevision (candidate_key, chapter_key, source_chapter_url, name, discovered_at, updated_at) " +
                    "VALUES ('${"a".repeat(64)}', 'chapter-key', 'https://example.invalid/1', 'chapter', 1, 1)",
            )

            connection.createStatement().execute(M0078_CanonicalIdentity().sql)

            val columns = connection.revisionColumns()
            assertTrue(
                columns.containsAll(
                    listOf(
                        "canonical_work_key",
                        "canonical_binding_role",
                        "canonical_binding_priority",
                        "canonical_binding_primary",
                        "canonical_binding_source_id",
                        "canonical_binding_manga_url",
                    ),
                ),
                "the snapshot columns are missing, got $columns",
            )

            connection
                .createStatement()
                .executeQuery("SELECT canonical_work_key, canonical_binding_role FROM chapterrevision")
                .use { rs ->
                    assertTrue(rs.next(), "the pre-existing revision must survive the migration")
                    assertNull(rs.getString(1), "a revision without a binding must not be backfilled")
                    assertNull(rs.getString(2), "a revision without a binding must have no role")
                }
        }
    }

    @Test
    fun `a manga belongs to at most one work`() {
        freshDatabase().use { connection ->
            val first = connection.work("work-a")
            val second = connection.work("work-b")
            val mangaId = connection.manga()

            connection.binding(first, mangaId)

            assertTrue(
                connection.fails(
                    "INSERT INTO canonicalsourcebinding (work, manga, role, priority, bound_at, updated_at) " +
                        "VALUES ($second, $mangaId, 'ACTIVE', 5, 1, 1)",
                ),
                "the unique manga index must reject a second claim on the same manga",
            )

            // null manga is distinct, so a detached binding never blocks a later re-bind
            connection.binding(second, null)
            connection.binding(second, null, priority = 1)
        }
    }

    @Test
    fun `at most one primary per work, and the marker is work scoped`() {
        freshDatabase().use { connection ->
            val first = connection.work("work-a")
            val second = connection.work("work-b")
            val firstManga = connection.manga("one")
            val secondManga = connection.manga("two")

            connection.binding(first, firstManga, primaryMarker = "work:$first")

            assertTrue(
                connection.fails(
                    "INSERT INTO canonicalsourcebinding (work, manga, priority, primary_marker, bound_at, updated_at) " +
                        "VALUES ($first, $secondManga, 9, 'work:$first', 1, 1)",
                ),
                "a work must never have two primaries",
            )

            // the same marker value for another work is what makes the marker work scoped
            connection.binding(second, secondManga, primaryMarker = "work:$second")

            val primaries =
                connection
                    .createStatement()
                    .executeQuery("SELECT COUNT(*) FROM canonicalsourcebinding WHERE primary_marker IS NOT NULL")
                    .use { rs ->
                        rs.next()
                        rs.getInt(1)
                    }
            assertEquals(2, primaries, "each work keeps its own primary")
        }
    }

    @Test
    fun `the ordering of a work's bindings is a permutation`() {
        freshDatabase().use { connection ->
            val first = connection.work("work-a")
            val second = connection.work("work-b")

            connection.binding(first, connection.manga("one"), priority = 0)

            assertTrue(
                connection.fails(
                    "INSERT INTO canonicalsourcebinding (work, manga, priority, bound_at, updated_at) " +
                        "VALUES ($first, NULL, 0, 1, 1)",
                ),
                "two bindings of one work must not share a priority",
            )

            // the same priority in another work is a different ordering, so it is allowed
            connection.binding(second, null, priority = 0)
        }
    }

    @Test
    fun `deleting a manga nulls the binding and keeps its audit snapshot`() {
        freshDatabase().use { connection ->
            val workId = connection.work()
            val mangaId = connection.manga()

            connection.binding(workId, mangaId, snapshot = "the series as it was")

            connection.createStatement().execute("DELETE FROM manga WHERE id = $mangaId")

            connection
                .createStatement()
                .executeQuery("SELECT manga, manga_title, work FROM canonicalsourcebinding")
                .use { rs ->
                    assertTrue(rs.next(), "the binding must survive the deletion of its manga")
                    rs.getInt(1)
                    assertTrue(rs.wasNull(), "the manga reference must be nulled, not the binding removed")
                    assertEquals("the series as it was", rs.getString(2), "the audit snapshot must survive")
                    assertEquals(workId, rs.getInt(3), "the work must be untouched")
                }

            // the canonical work itself is never affected by a source deletion
            connection.createStatement().executeQuery("SELECT COUNT(*) FROM canonicalwork").use { rs ->
                rs.next()
                assertEquals(1, rs.getInt(1))
            }
        }
    }

    @Test
    fun `deleting a work removes its bindings and nothing else`() {
        freshDatabase().use { connection ->
            val workId = connection.work()
            val mangaId = connection.manga()
            connection.binding(workId, mangaId)

            connection.createStatement().execute("DELETE FROM canonicalwork WHERE id = $workId")

            connection.createStatement().executeQuery("SELECT COUNT(*) FROM canonicalsourcebinding").use { rs ->
                rs.next()
                assertEquals(0, rs.getInt(1), "a work's bindings cascade with the work")
            }
            connection.createStatement().executeQuery("SELECT COUNT(*) FROM manga").use { rs ->
                rs.next()
                assertEquals(1, rs.getInt(1), "the source manga is never touched by a canonical deletion")
            }
        }
    }

    @Test
    fun `the invariants are indexes rather than conventions`() {
        freshDatabase().use { connection ->
            val names =
                mutableSetOf<String>().also { indexes ->
                    connection
                        .createStatement()
                        .executeQuery(
                            "SELECT INDEX_NAME FROM INFORMATION_SCHEMA.INDEXES WHERE TABLE_NAME = 'CANONICALSOURCEBINDING'",
                        ).use { rs ->
                            while (rs.next()) {
                                indexes += rs.getString(1).uppercase()
                            }
                        }
                }

            assertNotNull(names.firstOrNull { it.contains("CANONICAL_BINDING_MANGA") }, "unique manga index missing: $names")
            assertNotNull(names.firstOrNull { it.contains("CANONICAL_BINDING_PRIMARY") }, "unique primary index missing: $names")
            assertNotNull(names.firstOrNull { it.contains("CANONICAL_BINDING_PRIORITY") }, "unique priority index missing: $names")
        }
    }

    @Test
    fun `the unique indexes are on the columns the invariants are about`() {
        freshDatabase().use { connection ->
            val indexedColumnSets =
                mutableListOf<Set<String>>().also { sets ->
                    connection
                        .createStatement()
                        .executeQuery(
                            "SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.INDEX_COLUMNS " +
                                "WHERE TABLE_NAME IN ('CANONICALWORK', 'CANONICALSOURCEBINDING', 'CHAPTERREVISION') " +
                                "ORDER BY TABLE_NAME, INDEX_NAME, ORDINAL_POSITION",
                        ).use { rs ->
                            val columnsByIndex = linkedMapOf<String, MutableSet<String>>()
                            while (rs.next()) {
                                val key = rs.getString("TABLE_NAME") + "." + rs.getString("INDEX_NAME")
                                columnsByIndex.getOrPut(key) { linkedSetOf() }.add(rs.getString("COLUMN_NAME").uppercase())
                            }
                            sets += columnsByIndex.values
                        }
                }

            // the public identity the API addresses a work by
            assertTrue(indexedColumnSets.contains(setOf("WORK_KEY")))
            // one manga, one work
            assertTrue(indexedColumnSets.contains(setOf("MANGA")))
            // at most one primary per work, scoped by the marker that carries the work id
            assertTrue(indexedColumnSets.contains(setOf("PRIMARY_MARKER")))
            // the ordering of a work's bindings is a permutation
            assertTrue(indexedColumnSets.contains(setOf("WORK", "PRIORITY")))
            // the audit query the revision snapshot exists for
            assertTrue(indexedColumnSets.contains(setOf("CANONICAL_WORK_KEY", "ID")))
        }
    }

    @Test
    fun `the migration sql is portable across both supported dialects`() {
        val sql = M0078_CanonicalIdentity().sql

        // the identity syntax both H2 and PostgreSQL accept
        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"))
        // constructs only one of the two dialects would accept
        listOf("AUTO_INCREMENT", "SERIAL", "IDENTITY(", "ENGINE=", "UNSIGNED").forEach { dialectSpecific ->
            assertFalse(sql.contains(dialectSpecific), "migration must not use $dialectSpecific")
        }

        // every column the runtime table objects map is really created, so a downgrade cannot silently
        // drop one of them
        listOf(
            "work_key",
            "title",
            "duplicate_strategy",
            "preferred_scanlator",
            "created_at",
            "updated_at",
            "work INT",
            "manga INT",
            "role",
            "priority",
            "primary_marker",
            "manga_title",
            "manga_url",
            "source_id",
            "source_name",
            "bound_at",
        ).forEach { column -> assertTrue(sql.contains(column), "missing column $column") }

        // the manga reference is what keeps the audit after a source deletion, and the work is what the
        // bindings cascade with; neither may be tightened by accident
        val flattened = sql.replace(Regex("\\s+"), " ")
        assertTrue(flattened.contains("REFERENCES manga(ID) ON DELETE SET NULL"), "the manga reference must null out")
        assertTrue(flattened.contains("REFERENCES canonicalwork(ID) ON DELETE CASCADE"), "a work's bindings cascade")

        // the four revision snapshot columns are plain nullable columns, never a foreign key: the audit
        // has to outlive the work it names
        listOf(
            "canonical_work_key VARCHAR(64) NULL",
            "canonical_binding_role VARCHAR(64) NULL",
            "canonical_binding_priority INT NULL",
            "canonical_binding_primary BOOLEAN NULL",
            "canonical_binding_source_id BIGINT NULL",
            "canonical_binding_manga_url VARCHAR(2048) NULL",
        ).forEach { column -> assertTrue(sql.contains(column), "missing revision column $column") }
    }
}
