package suwayomi.tachidesk.server.database

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import suwayomi.tachidesk.manga.model.dataclass.MangaAcquisitionPolicy
import suwayomi.tachidesk.server.database.migration.M0080_ArchiveDefaultAcquisitionPolicy
import suwayomi.tachidesk.test.ApplicationTest
import java.sql.Connection
import java.sql.DriverManager

/**
 * Migration-level guarantees of the optional per-series acquisition policy.
 *
 * Uses the migration's own SQL against a throwaway H2 database that carries the pre-M0080 column
 * shape, so what is asserted is exactly what the migration changes.
 */
class M0080ArchiveDefaultAcquisitionPolicyTest : ApplicationTest() {
    private fun Connection.policyOf(id: Long): String? =
        createStatement().executeQuery("SELECT acquisition_policy FROM manga WHERE id = $id").use { rs ->
            rs.next()
            rs.getString(1)
        }

    private fun database(): Connection =
        DriverManager
            .getConnection("jdbc:h2:mem:archive_policy_${System.nanoTime()};DB_CLOSE_DELAY=-1", "sa", "")
            .also { connection ->
                // the shape M0065 left behind: the column is NOT NULL and supplies its own default
                connection.createStatement().execute(
                    "CREATE TABLE manga (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "title VARCHAR(512), url VARCHAR(2048), " +
                        "acquisition_policy VARCHAR(256) NOT NULL DEFAULT '${MangaAcquisitionPolicy.MANUAL.name}')",
                )
            }

    @Test
    fun `existing rows stay explicit overrides and new rows inherit null`() {
        val connection = database()
        connection.createStatement().execute("INSERT INTO manga (title, url) VALUES ('Existing', '/existing')")
        connection.createStatement().execute(
            "INSERT INTO manga (title, url, acquisition_policy) VALUES ('Paused', '/paused', '${MangaAcquisitionPolicy.PAUSED.name}')",
        )

        connection.createStatement().execute(M0080_ArchiveDefaultAcquisitionPolicy().h2Query())

        assertEquals(MangaAcquisitionPolicy.MANUAL.name, connection.policyOf(1), "an existing value must survive untouched")
        assertEquals(MangaAcquisitionPolicy.PAUSED.name, connection.policyOf(2), "a non-default existing value must survive untouched")

        connection.createStatement().execute("INSERT INTO manga (title, url) VALUES ('New', '/new')")
        assertNull(connection.policyOf(3), "the DB default must be gone so a new row inherits")
    }

    @Test
    fun `the postgres variant drops the not null and default constraints`() {
        val sql = M0080_ArchiveDefaultAcquisitionPolicy().postgresQuery()

        assertTrue(sql.contains("ALTER COLUMN acquisition_policy DROP NOT NULL"))
        assertTrue(sql.contains("ALTER COLUMN acquisition_policy DROP DEFAULT"))
    }
}
