package suwayomi.tachidesk.server.database.migration

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import de.neonew.exposed.migrations.helpers.SQLMigration
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionPageAlignmentState
import suwayomi.tachidesk.manga.model.dataclass.ChapterVisualAnalysisState

// Adds the durable visual page comparison of a revision against the baseline it was classified
// against.
//
// M0076 added *whether* a candidate differs from what is archived (a byte-level comparison). That
// answer is necessary but not sufficient for review: a re-release that changed one page of forty, a
// re-release that only added a credit page and a re-release whose every page was re-encoded all
// look identical to a whole-chapter hash. This migration adds the dimension that tells them apart,
// and it is a dimension of its own because it can be pending, running, limited or failed while the
// acquisition, archive, publication and retention dimensions are unaffected.
//
// `visual_analysis_state` defaults to NOT_REQUIRED, not QUEUED: a row that already existed when this
// migration runs was never analysed, and `ADD COLUMN ... NOT NULL DEFAULT` hands it that value in
// both dialects. QUEUED means an analysis is still owed, which is only ever written explicitly by
// the classification that found new content against a baseline. That is also why no backfill runs:
// a database without the dimension must not wake up believing it owes thousands of comparisons.
//
// The baseline of the analysis is the existing `comparison_baseline_revision` column rather than a
// second reference, so the fence that protects a commit ("has the active revision moved since this
// analysis started") reads exactly one persisted value.
//
// `chapterrevisioncomparison` holds one summary per candidate and `chapterrevisioncomparisonpage`
// the ordered alignment behind it. The summary's reference to its candidate cascades, because an
// alignment without its candidate is meaningless, while its reference to the baseline is SET NULL -
// a pruned or replaced baseline must never delete the audit of a comparison that used it.
//
// A page row carries both the exact digest and the perceptual fingerprint of each side, so the
// alignment can be re-read later without the images. `thumbnail_relative_path` is an internal
// staging location and is deliberately never surfaced through the API; it exists so a review UI can
// render a preview without re-decoding a whole CBZ.
@Suppress("ClassName", "unused")
class M0077_ChapterRevisionVisualAnalysis : SQLMigration() {
    // language=sql
    override val sql: String =
        """
        ALTER TABLE chapterrevision ADD COLUMN visual_analysis_state VARCHAR(64) NOT NULL DEFAULT '${ChapterVisualAnalysisState.NOT_REQUIRED.name}';
        ALTER TABLE chapterrevision ADD COLUMN visual_analysis_attempts INT NOT NULL DEFAULT 0;
        ALTER TABLE chapterrevision ADD COLUMN visual_analysis_last_error VARCHAR(1024) NULL;
        -- machine readable category of the same failure: the message is for a human, this is what a
        -- manifest or a client can switch on without parsing prose
        ALTER TABLE chapterrevision ADD COLUMN visual_analysis_last_failure VARCHAR(64) NULL;
        ALTER TABLE chapterrevision ADD COLUMN visual_analysis_last_attempt_at BIGINT NULL;
        -- earliest instant this candidate's analysis may run; null while it is due immediately
        ALTER TABLE chapterrevision ADD COLUMN visual_analysis_next_attempt_at BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN visual_analysis_completed_at BIGINT NULL;

        -- the worker claims the earliest due candidate, so the claim index carries both the state and
        -- the persisted due time
        CREATE INDEX chapter_revision_visual_analysis_backlog_idx ON chapterrevision (visual_analysis_state, visual_analysis_next_attempt_at, id);

        CREATE TABLE IF NOT EXISTS chapterrevisioncomparison (
            -- identity syntax both H2 and PostgreSQL accept
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            -- the candidate the comparison describes; unique, so one candidate has one summary
            revision INT NOT NULL,
            -- the revision that was actually compared against; nulled instead of cascading so a
            -- pruned or deleted baseline never erases the audit that used it
            baseline_revision INT NULL,
            baseline_page_count INT NOT NULL,
            candidate_page_count INT NOT NULL,
            exact_count INT NOT NULL,
            visually_equivalent_count INT NOT NULL,
            modified_count INT NOT NULL,
            added_count INT NOT NULL,
            removed_count INT NOT NULL,
            -- how many aligned rows the summary describes, so a reader can page without counting
            aligned_count INT NOT NULL,
            -- the threshold this summary was produced with, kept so an old summary stays interpretable
            hamming_threshold INT NOT NULL,
            algorithm_version VARCHAR(64) NOT NULL,
            all_pages_visually_equivalent BOOLEAN NOT NULL,
            has_limitations BOOLEAN NOT NULL,
            limitations VARCHAR(1024) NULL,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT FK_CHAPTERREVISIONCOMPARISON_REVISION__ID
                FOREIGN KEY (revision) REFERENCES chapterrevision(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT,
            CONSTRAINT FK_CHAPTERREVISIONCOMPARISON_BASELINE__ID
                FOREIGN KEY (baseline_revision) REFERENCES chapterrevision(ID)
                ON DELETE SET NULL ON UPDATE RESTRICT
        );

        -- one summary per candidate: re-analysing replaces it instead of accumulating duplicates
        CREATE UNIQUE INDEX chapter_revision_comparison_revision_idx ON chapterrevisioncomparison (revision);
        CREATE INDEX chapter_revision_comparison_created_idx ON chapterrevisioncomparison (created_at, id);

        CREATE TABLE IF NOT EXISTS chapterrevisioncomparisonpage (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            comparison INT NOT NULL,
            -- denormalised candidate id: the alignment is paged per candidate without a join
            revision INT NOT NULL,
            -- position of this aligned row inside the alignment, which is also its page order
            ordinal INT NOT NULL,
            baseline_page_index INT NULL,
            candidate_page_index INT NULL,
            state VARCHAR(32) NOT NULL DEFAULT '${ChapterRevisionPageAlignmentState.MODIFIED.name}',
            -- whole-page digests, so an EXACT row stays provable without the images
            baseline_exact_hash VARCHAR(64) NULL,
            candidate_exact_hash VARCHAR(64) NULL,
            -- 128 bit perceptual fingerprints; null when the page could not be decoded
            baseline_perceptual_hash VARCHAR(64) NULL,
            candidate_perceptual_hash VARCHAR(64) NULL,
            hamming_distance INT NULL,
            baseline_width INT NULL,
            baseline_height INT NULL,
            candidate_width INT NULL,
            candidate_height INT NULL,
            baseline_size BIGINT NULL,
            candidate_size BIGINT NULL,
            -- internal staging locations of the review previews; never exposed through the API.
            -- Both sides are kept separately, because a MODIFIED row is reviewed by putting the two
            -- versions of the page next to each other, and an ADDED or REMOVED row only has one side.
            baseline_thumbnail_relative_path VARCHAR(1024) NULL,
            baseline_thumbnail_sha256 VARCHAR(64) NULL,
            baseline_thumbnail_size BIGINT NULL,
            candidate_thumbnail_relative_path VARCHAR(1024) NULL,
            candidate_thumbnail_sha256 VARCHAR(64) NULL,
            candidate_thumbnail_size BIGINT NULL,
            created_at BIGINT NOT NULL,
            CONSTRAINT FK_CHAPTERREVISIONCOMPARISONPAGE_COMPARISON__ID
                FOREIGN KEY (comparison) REFERENCES chapterrevisioncomparison(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT,
            CONSTRAINT FK_CHAPTERREVISIONCOMPARISONPAGE_REVISION__ID
                FOREIGN KEY (revision) REFERENCES chapterrevision(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT
        );

        -- the alignment of one summary is read strictly in order
        CREATE UNIQUE INDEX chapter_revision_comparison_page_order_idx ON chapterrevisioncomparisonpage (comparison, ordinal);
        -- the review UI pages the alignment of a candidate directly, and a state filter is what makes
        -- "show me only the modified pages" a single index scan
        CREATE INDEX chapter_revision_comparison_page_revision_idx ON chapterrevisioncomparisonpage (revision, state, ordinal);
        """.trimIndent()
}
