package suwayomi.tachidesk.server.database.migration

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import de.neonew.exposed.migrations.helpers.SQLMigration
import suwayomi.tachidesk.manga.model.dataclass.ChapterIntegrityAuditItemState
import suwayomi.tachidesk.manga.model.dataclass.ChapterIntegrityAuditKind
import suwayomi.tachidesk.manga.model.dataclass.ChapterIntegrityAuditSessionState
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionIntegrityState

// Adds the archive integrity audit and the rollback record.
//
// An integrity audit answers a question nothing else in the archive can: the persisted archive state
// says a revision *was* durably committed, it does not say the object is still there. The audit
// therefore re-reads remote storage directly and records what it saw, in a dimension of its own
// (`chapterrevision.integrity_state`). An audit finding never rewrites the archive state and never
// deletes content: a revision that is REMOTE_CONFIRMED and later reported MISSING was durably
// archived once, and both facts have to stay readable at the same time.
//
// This migration is additive on purpose:
//
//   * it creates three new tables (audit session, audit item, audit schedule) and one audit trail
//     (rollback record);
//   * it adds four nullable/defaulted columns to `chapterrevision`, all of them describing the new
//     integrity dimension. Nothing is backfilled, so every revision that already existed decodes as
//     NEVER_AUDITED, which is exactly what it is: nobody ever checked it.
//
// The audit item's snapshot columns - revision id, candidate key, both relative artifact paths and
// both sizes and digests - are plain values rather than references. What a run verified has to stay
// readable after the revision row was edited or removed, and an artifact location that a later edit
// changed must not silently change what that run checked.
//
// `chapterintegrityauditsession.active_marker` holds a constant while a session is RUNNING or PAUSED
// and is null otherwise, so its unique index is what makes "at most one active audit" a database
// invariant. Nulls are distinct in a unique index in both dialects, so terminal sessions never
// conflict with each other.
//
// The schedule is a singleton row (`id = 1` as the primary key plus a check constraint naming that
// single accepted id) exactly like the sweep schedule: a persisted due instant is what lets a restart
// resume what was owed instead of inventing an audit, and `retry_not_before` is separate from
// `next_due_at` so a start that failed does not consume the occurrence it owes.
@Suppress("ClassName", "unused")
class M0079_ChapterRevisionIntegrityAudit : SQLMigration() {
    // language=sql
    override val sql: String =
        """
        CREATE TABLE IF NOT EXISTS chapterintegrityauditsession (
            -- identity syntax both H2 and PostgreSQL accept
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind VARCHAR(64) NOT NULL DEFAULT '${ChapterIntegrityAuditKind.MANUAL_RECENT.name}',
            state VARCHAR(64) NOT NULL DEFAULT '${ChapterIntegrityAuditSessionState.RUNNING.name}',
            -- holds the constant marker while this session is running or paused, null otherwise
            active_marker VARCHAR(64) NULL,
            -- how many newest revisions per series were selected; null when every revision was
            newest_per_manga INT NULL,
            item_delay_seconds BIGINT NOT NULL DEFAULT 2,
            retry_seconds BIGINT NOT NULL DEFAULT 300,
            max_attempts INT NOT NULL DEFAULT 3,
            next_item_at BIGINT NULL,
            last_item_at BIGINT NULL,
            started_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            finished_at BIGINT NULL,
            paused_at BIGINT NULL,
            cancelled_at BIGINT NULL
        );

        -- at most one active audit; nulls are distinct, so terminal sessions never conflict
        CREATE UNIQUE INDEX chapter_integrity_audit_session_active_idx ON chapterintegrityauditsession (active_marker);
        -- the worker claims the oldest session that is currently allowed to run
        CREATE INDEX chapter_integrity_audit_session_claim_idx ON chapterintegrityauditsession (state, next_item_at, id);

        CREATE TABLE IF NOT EXISTS chapterintegrityaudititem (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session INT NOT NULL,
            -- what was audited, as it was when the run started; deliberately not a foreign key
            revision INT NULL,
            chapter_key VARCHAR(64) NOT NULL,
            candidate_key VARCHAR(64) NOT NULL,
            manga_id INT NULL,
            chapter_id INT NULL,
            series_title VARCHAR(512) NULL,
            chapter_name VARCHAR(512) NOT NULL,
            -- the exact immutable artifacts this run expected on remote storage
            cbz_path VARCHAR(2048) NOT NULL,
            cbz_sha256 VARCHAR(64) NOT NULL,
            cbz_size BIGINT NOT NULL,
            manifest_path VARCHAR(2048) NOT NULL,
            manifest_sha256 VARCHAR(64) NOT NULL,
            manifest_size BIGINT NOT NULL,
            state VARCHAR(64) NOT NULL DEFAULT '${ChapterIntegrityAuditItemState.PENDING.name}',
            attempts INT NOT NULL DEFAULT 0,
            last_error VARCHAR(1024) NULL,
            due_at BIGINT NULL,
            started_at BIGINT NULL,
            finished_at BIGINT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT FK_CHAPTERINTEGRITYAUDITITEM_SESSION__ID
                FOREIGN KEY (session) REFERENCES chapterintegrityauditsession(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT
        );

        -- the worker claims the earliest claimable revision of one session, ordered by its due time
        CREATE INDEX chapter_integrity_audit_item_backlog_idx ON chapterintegrityaudititem (session, state, due_at, id);
        -- the per-session listing is ordered by id and filtered only by session
        CREATE INDEX chapter_integrity_audit_item_session_idx ON chapterintegrityaudititem (session, id);

        CREATE TABLE IF NOT EXISTS chapterintegrityauditschedule (
            -- the primary key plus the check below make a second schedule impossible; the primary key
            -- alone would still accept any other id
            id INT NOT NULL PRIMARY KEY,
            next_due_at BIGINT NOT NULL,
            last_run_at BIGINT NULL,
            last_session_id INT NULL,
            -- a start that failed defers its retry without consuming the occurrence it owes
            retry_not_before BIGINT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT CHK_CHAPTERINTEGRITYAUDITSCHEDULE_SINGLETON CHECK (id = 1)
        );

        -- the integrity dimension of a revision, independent from its archive durability.
        --
        -- The default is NEVER_AUDITED rather than any finding: an existing revision was never
        -- checked, so the migration hands it exactly that state instead of inventing an audit.
        ALTER TABLE chapterrevision ADD COLUMN integrity_state VARCHAR(64) NOT NULL DEFAULT '${ChapterRevisionIntegrityState.NEVER_AUDITED.name}';
        ALTER TABLE chapterrevision ADD COLUMN integrity_last_audited_at BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN integrity_last_audit_session INT NULL;
        ALTER TABLE chapterrevision ADD COLUMN integrity_last_error VARCHAR(1024) NULL;

        -- the audit backlog is browsed per state, which is what a findings view pages through
        CREATE INDEX chapter_revision_integrity_state_idx ON chapterrevision (integrity_state, id);

        CREATE TABLE IF NOT EXISTS chapterrevisionrollback (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            -- the chapter identity the decision was about
            chapter_key VARCHAR(64) NOT NULL,
            -- the revision that was active before, and the one that became active again; both are
            -- plain snapshots so the record survives the removal of either revision
            from_revision INT NULL,
            to_revision INT NULL,
            rolled_back_at BIGINT NOT NULL
        );

        -- the history of one chapter identity, newest first
        CREATE INDEX chapter_revision_rollback_identity_idx ON chapterrevisionrollback (chapter_key, rolled_back_at, id);
        -- the global history, newest first, which is the paginated audit query
        CREATE INDEX chapter_revision_rollback_history_idx ON chapterrevisionrollback (rolled_back_at, id);
        """.trimIndent()
}
