package suwayomi.tachidesk.server.database.migration

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import de.neonew.exposed.migrations.helpers.SQLMigration
import suwayomi.tachidesk.manga.model.dataclass.BackupRestoreAuditLevel
import suwayomi.tachidesk.manga.model.dataclass.BackupRestoreHandoffState
import suwayomi.tachidesk.manga.model.dataclass.BackupRestoreJobState
import suwayomi.tachidesk.manga.model.dataclass.BackupRestorePhase

// Makes an ordinary (non-sync) `.tachibk` restore durable and resumable.
//
// A restore of the 3,435 series baseline takes long enough that a shutdown must not throw it away, so
// the job - not the process - owns the progress: the uploaded bytes are streamed once to a staged
// file outside the database, and the row records only what is needed to continue from where the
// previous process stopped. No backup payload, no chapter history and no credential is ever stored
// here: the staged file is the only copy of the payload, and `staged_relative_path` is relative to
// the staging root so the row can never point outside it.
//
// `flags`, `category_mapping` and `handoff_category_overrides` are compact, version-independent
// encodings rather than serialized objects, so an old row stays readable after the application
// changes. `category_mapping` is persisted rather than rebuilt so a resume at the MANGA phase does
// not have to re-run the category import to learn the mapping it needs.
//
// `audit_key` gives every audit row a deterministic identity inside its job, so an interrupted
// restore that reprocesses a series can neither duplicate a report nor inflate the error count, and a
// series that later succeeds can have its earlier failure withdrawn.
//
// `archivebootstrapsession.origin_key` records which restore a bootstrap was started for. A restore
// is a long operation that can be interrupted between starting its bootstrap and recording that it
// did, so the origin has to be part of the schema: without it a resume cannot tell "this run is
// already mine" from "somebody else's run is active". M0074 created the table and stays untouched.
//
// Nothing is backfilled: a database without a job simply has no restore in flight.
@Suppress("ClassName", "unused")
class M0075_BackupRestoreJob : SQLMigration() {
    // language=sql
    override val sql: String =
        """
        CREATE TABLE IF NOT EXISTS backuprestorejob (
            -- identity syntax both H2 and PostgreSQL accept
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            -- random, not a timestamp: the id is also the staged file name and must not be guessable
            restore_id VARCHAR(64) NOT NULL,
            state VARCHAR(64) NOT NULL DEFAULT '${BackupRestoreJobState.QUEUED.name}',
            phase VARCHAR(64) NOT NULL DEFAULT '${BackupRestorePhase.PENDING.name}',
            staged_relative_path VARCHAR(1024) NOT NULL,
            staged_size BIGINT NOT NULL,
            staged_sha256 VARCHAR(64) NOT NULL,
            flags VARCHAR(64) NOT NULL,
            category_mapping VARCHAR(4096) NOT NULL DEFAULT '',
            manga_index INT NOT NULL DEFAULT 0,
            manga_count INT NOT NULL DEFAULT 0,
            error_count INT NOT NULL DEFAULT 0,
            last_error VARCHAR(1024) NULL,
            handoff_state VARCHAR(64) NOT NULL DEFAULT '${BackupRestoreHandoffState.NONE.name}',
            handoff_default_policy VARCHAR(64) NULL,
            handoff_category_overrides TEXT NOT NULL DEFAULT '',
            handoff_session_id INT NULL,
            handoff_error VARCHAR(1024) NULL,
            staged_deleted_at BIGINT NULL,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            started_at BIGINT NULL,
            finished_at BIGINT NULL,
            cancelled_at BIGINT NULL
        );

        -- the restore id is what the API returns, so it is the lookup key
        CREATE UNIQUE INDEX backup_restore_job_restore_id_idx ON backuprestorejob (restore_id);
        -- the worker claims the oldest queued job
        CREATE INDEX backup_restore_job_claim_idx ON backuprestorejob (state, id);

        CREATE TABLE IF NOT EXISTS backuprestorejobaudit (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job INT NOT NULL,
            level VARCHAR(64) NOT NULL DEFAULT '${BackupRestoreAuditLevel.MANGA_ERROR.name}',
            phase VARCHAR(64) NOT NULL,
            manga_index INT NULL,
            source_id BIGINT NULL,
            source_name VARCHAR(256) NULL,
            -- bounded on purpose: it is exposed through authenticated GraphQL
            message VARCHAR(1024) NOT NULL,
            -- deterministic identity of the report inside its job, e.g. 'MANGA:42'
            audit_key VARCHAR(128) NOT NULL DEFAULT '',
            created_at BIGINT NOT NULL,
            CONSTRAINT FK_BACKUPRESTOREJOBAUDIT_JOB__ID
                FOREIGN KEY (job) REFERENCES backuprestorejob(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT
        );

        -- audit rows are always listed for one job, ordered by id
        CREATE INDEX backup_restore_job_audit_job_idx ON backuprestorejobaudit (job, id);
        -- and a report can only exist once per job, which is what makes re-recording idempotent
        CREATE UNIQUE INDEX backup_restore_job_audit_key_idx ON backuprestorejobaudit (job, audit_key);

        -- the restore a bootstrap was started for; unique so a resumed restore finds its own run
        ALTER TABLE archivebootstrapsession ADD COLUMN origin_key VARCHAR(128) NULL;
        CREATE UNIQUE INDEX archive_bootstrap_session_origin_idx ON archivebootstrapsession (origin_key);
        """.trimIndent()
}
