package suwayomi.tachidesk.server.database.migration

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import de.neonew.exposed.migrations.helpers.SQLMigration
import suwayomi.tachidesk.graphql.types.DatabaseType
import suwayomi.tachidesk.server.serverConfig

// Adds the accepted-revision lifecycle, the active-library publication bookkeeping and the durable
// post-publication outbox, and brings the SyncYomi manga triggers in line with the new
// `accepted_revision_retention` column.
//
// M0067-M0069 stay untouched: they already created and extended the revision table in released form.
//
// `chapter_key` is the immutable identity of a source chapter and groups its revisions. Rows created
// before this migration can only belong to one identity each - no revision history exists yet - so
// backfilling them from their own `candidate_key` is exact, not an approximation.
@Suppress("ClassName", "unused")
class M0070_ChapterRevisionPublication : SQLMigration() {
    override val sql: String = columnAndTableSql() + "\n" + syncYomiSql()

    // language=sql
    private fun columnAndTableSql(): String =
        """
        ALTER TABLE manga ADD COLUMN accepted_revision_retention INT NULL;

        ALTER TABLE chapterrevision ADD COLUMN chapter_key VARCHAR(64) NULL;
        UPDATE chapterrevision SET chapter_key = candidate_key WHERE chapter_key IS NULL;
        ALTER TABLE chapterrevision ALTER COLUMN chapter_key SET NOT NULL;

        ALTER TABLE chapterrevision ADD COLUMN active_chapter_key VARCHAR(64) NULL;
        ALTER TABLE chapterrevision ADD COLUMN accepted_at BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN activated_at BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN superseded_at BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN publication_attempts INT NOT NULL DEFAULT 0;
        ALTER TABLE chapterrevision ADD COLUMN publication_last_error VARCHAR(4096) NULL;
        ALTER TABLE chapterrevision ADD COLUMN publication_last_attempt_at BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN active_cbz_path VARCHAR(2048) NULL;
        ALTER TABLE chapterrevision ADD COLUMN active_cbz_hash VARCHAR(64) NULL;
        ALTER TABLE chapterrevision ADD COLUMN active_cbz_size BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN published_at BIGINT NULL;

        CREATE INDEX chapter_revision_identity_idx ON chapterrevision (chapter_key, id);
        CREATE UNIQUE INDEX chapter_revision_active_identity_idx ON chapterrevision (active_chapter_key);
        CREATE INDEX chapter_revision_publication_backlog_idx
            ON chapterrevision (active_chapter_key, publication_state, id);

        CREATE TABLE IF NOT EXISTS chapterpublicationevent (
            -- identity syntax both H2 and PostgreSQL accept (the MySQL auto-increment keyword is not)
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chapter_revision INT NULL,
            chapter_key VARCHAR(64) NOT NULL,
            candidate_key VARCHAR(64) NOT NULL,
            manga_id INT NOT NULL,
            event_type VARCHAR(64) NOT NULL,
            payload TEXT NOT NULL,
            occurred_at BIGINT NOT NULL,
            attempts INT NOT NULL DEFAULT 0,
            last_attempt_at BIGINT NULL,
            last_error VARCHAR(4096) NULL,
            delivered_at BIGINT NULL,
            CONSTRAINT FK_CHAPTERPUBLICATIONEVENT_CHAPTER_REVISION__ID
                FOREIGN KEY (chapter_revision) REFERENCES chapterrevision(ID)
                ON DELETE SET NULL ON UPDATE RESTRICT
        );
        CREATE INDEX chapter_publication_event_backlog_idx ON chapterpublicationevent (delivered_at, id);
        """.trimIndent()

    private fun syncYomiSql(): String =
        when (serverConfig.databaseType.value) {
            DatabaseType.POSTGRESQL -> postgresQuery()
            DatabaseType.H2 -> h2Query()
        }

    // M0066 replaced these functions to watch acquisition_policy; they are replaced again here so the
    // new column is visible to incremental sync as well. Triggers and their BEFORE ordering are left
    // untouched, which is what lets update_manga_last_modified_at still see the bumped version.
    // language=postgresql
    fun postgresQuery(): String =
        """
        CREATE OR REPLACE FUNCTION update_manga_version()
        RETURNS trigger AS $$
        BEGIN
            IF NOT NEW.is_syncing
               AND ROW(NEW.url, NEW.description, NEW.in_library, NEW.acquisition_policy,
                       NEW.accepted_revision_retention)
                   IS DISTINCT FROM
                   ROW(OLD.url, OLD.description, OLD.in_library, OLD.acquisition_policy,
                       OLD.accepted_revision_retention)
            THEN
                NEW.version := OLD.version + 1;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE OR REPLACE FUNCTION update_manga_last_modified_at()
        RETURNS trigger AS $$
        BEGIN
            IF NEW.is_syncing THEN
                RETURN NEW;
            END IF;

            IF TG_OP = 'UPDATE'
               AND ROW(NEW.url, NEW.description, NEW.in_library, NEW.version, NEW.acquisition_policy,
                       NEW.accepted_revision_retention)
                   IS NOT DISTINCT FROM
                   ROW(OLD.url, OLD.description, OLD.in_library, OLD.version, OLD.acquisition_policy,
                       OLD.accepted_revision_retention)
            THEN
                RETURN NEW;
            END IF;

            NEW.last_modified_at := EXTRACT(EPOCH FROM NOW());
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """.trimIndent()

    // On H2 the existing manga triggers are recreated against replacement classes because the M0066
    // classes must keep working when this migration has not run yet.
    // language=h2
    fun h2Query(): String =
        """
        DROP TRIGGER IF EXISTS update_manga_version;
        CREATE TRIGGER update_manga_version
        BEFORE UPDATE ON manga
        FOR EACH ROW
        CALL "suwayomi.tachidesk.server.database.trigger.UpdateMangaVersionWithArchivalRetentionTrigger";

        DROP TRIGGER IF EXISTS update_manga_last_modified_at;
        CREATE TRIGGER update_manga_last_modified_at
        BEFORE UPDATE ON manga
        FOR EACH ROW
        CALL "suwayomi.tachidesk.server.database.trigger.UpdateMangaLastModifiedAtWithArchivalRetentionTrigger";
        """.trimIndent()
}
