package suwayomi.tachidesk.server.database.migration

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import de.neonew.exposed.migrations.helpers.SQLMigration
import suwayomi.tachidesk.manga.model.dataclass.ArchiveBootstrapItemState
import suwayomi.tachidesk.manga.model.dataclass.ArchiveBootstrapState

// Adds the durable archive bootstrap: one session per backfill run plus one item per series.
//
// The intent is deliberately runtime state, not a schema change to the library: an item snapshots the
// series id, source id, title and categories it was created from, and never references them, so a
// deleted series or a removed source row can never erase the audit record of what a run did. Only the
// item -> session relationship is a real foreign key, because an item is meaningless without its run.
//
// Nothing is backfilled: a database without a session simply has nothing to bootstrap.
@Suppress("ClassName", "unused")
class M0074_ArchiveBootstrap : SQLMigration() {
    // language=sql
    override val sql: String =
        """
        CREATE TABLE IF NOT EXISTS archivebootstrapsession (
            -- identity syntax both H2 and PostgreSQL accept
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            state VARCHAR(64) NOT NULL DEFAULT '${ArchiveBootstrapState.RUNNING.name}',
            active_marker VARCHAR(64) NULL,
            default_policy VARCHAR(64) NOT NULL,
            category_policy_overrides TEXT NOT NULL DEFAULT '',
            inter_item_delay_seconds BIGINT NOT NULL DEFAULT 2,
            retry_seconds BIGINT NOT NULL DEFAULT 300,
            max_attempts INT NOT NULL DEFAULT 3,
            next_item_at BIGINT NULL,
            last_item_at BIGINT NULL,
            started_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            finished_at BIGINT NULL,
            paused_at BIGINT NULL,
            cancelled_at BIGINT NULL
        );

        -- "at most one active bootstrap" is a database invariant: the marker is non-null only for a
        -- RUNNING or PAUSED session and both dialects treat nulls as distinct in a unique index
        CREATE UNIQUE INDEX archive_bootstrap_active_idx ON archivebootstrapsession (active_marker);
        CREATE INDEX archive_bootstrap_session_claim_idx ON archivebootstrapsession (state, next_item_at, id);

        CREATE TABLE IF NOT EXISTS archivebootstrapitem (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session INT NOT NULL,
            manga_id INT NULL,
            source_id BIGINT NULL,
            title VARCHAR(512) NOT NULL,
            manga_url VARCHAR(2048) NULL,
            -- a series can belong to many categories, so this audit snapshot is not length limited
            category_ids TEXT NOT NULL DEFAULT '',
            policy VARCHAR(64) NOT NULL,
            state VARCHAR(64) NOT NULL DEFAULT '${ArchiveBootstrapItemState.PENDING.name}',
            attempts INT NOT NULL DEFAULT 0,
            last_error VARCHAR(4096) NULL,
            candidate_count INT NULL,
            due_at BIGINT NULL,
            started_at BIGINT NULL,
            finished_at BIGINT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT FK_ARCHIVEBOOTSTRAPITEM_SESSION__ID
                FOREIGN KEY (session) REFERENCES archivebootstrapsession(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT
        );

        CREATE INDEX archive_bootstrap_item_backlog_idx ON archivebootstrapitem (session, state, due_at, id);
        CREATE INDEX archive_bootstrap_item_session_idx ON archivebootstrapitem (session, id);
        """.trimIndent()
}
