package suwayomi.tachidesk.server.database.migration

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import de.neonew.exposed.migrations.helpers.SQLMigration
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionComparisonState
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionSweepItemState
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionSweepKind
import suwayomi.tachidesk.manga.model.dataclass.ChapterRevisionSweepSessionState

// Makes periodic and manual revision sweeps durable, and gives every revision an independent
// content-comparison dimension.
//
// A sweep is the only source-independent way to notice that a source re-released a chapter: the
// extension API exposes no revision id, updated time or digest, so the content has to be fetched
// again and compared. A sweep is therefore long running by definition - the newest ten chapters of
// 3,435 series is 34,350 items - which means the *run*, not the process, has to own its progress.
//
// The schedule is a single row rather than a computed next-due time, so "when is the next sweep due"
// survives a restart and can only be advanced by the worker that actually started a run. That is
// what keeps a long outage from turning into a catch-up storm of missed intervals.
//
// Historical sweeps are audits: `chapterrevisionsweepitem` snapshots the series, chapter and policy
// it was created for instead of referencing them, so deleting a series, a chapter or a source never
// erases what a run did. Only the owning session is a real reference, and it cascades.
//
// `chapterrevision.sweep_item` is the binding between an item and the exactly-one candidate it may
// create. It is unique, so retrying an item reuses its candidate instead of recording a second one,
// while two different items always produce two different candidates. It is nullable because most
// candidates come from ordinary reconciliation, a bootstrap or a metadata change.
//
// `comparison_state`, `comparison_baseline_revision`, `compared_at` and `comparison_error` form the
// content-comparison dimension. It is deliberately separate from every lifecycle dimension: a
// revision can be `CONTENT_CHANGED` and still be archived, or `EXACT_MATCH` and never archived at
// all. The baseline is a self reference with ON DELETE SET NULL so pruning a baseline never removes
// the audit of the comparison that used it.
//
// `comparison_cleanup_due_at` is the persisted schedule of the staged-pages removal for an
// `EXACT_MATCH` revision. Its indexed due time is what the sweep worker sleeps on, so a removal that
// fails right now is retried at a known instant instead of waiting for the next monthly run.
//
// Nothing is backfilled as work: a database without a schedule simply has no sweep due, and every
// existing revision becomes `NOT_EVALUATED` - a durable record that it was never compared - rather
// than `PENDING`, which would claim a comparison that no run ever owes.
@Suppress("ClassName", "unused")
class M0076_ChapterRevisionSweep : SQLMigration() {
    // language=sql
    override val sql: String =
        """
        CREATE TABLE IF NOT EXISTS chapterrevisionsweepsession (
            -- identity syntax both H2 and PostgreSQL accept
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind VARCHAR(64) NOT NULL DEFAULT '${ChapterRevisionSweepKind.MANUAL_RECENT.name}',
            state VARCHAR(64) NOT NULL DEFAULT '${ChapterRevisionSweepSessionState.RUNNING.name}',
            -- holds a constant only while the session is RUNNING or PAUSED, so its unique index is
            -- what enforces "at most one active sweep" across every server instance
            active_marker VARCHAR(64) NULL,
            -- how many newest chapters per series were selected; null means the whole history
            newest_per_series INT NULL,
            -- pacing snapshotted at start, so a later settings change cannot alter a live run
            item_delay_seconds BIGINT NOT NULL DEFAULT 2,
            retry_seconds BIGINT NOT NULL DEFAULT 300,
            max_attempts INT NOT NULL DEFAULT 3,
            -- earliest instant the next item of this session may be processed; the global rate limit
            next_item_at BIGINT NULL,
            last_item_at BIGINT NULL,
            started_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            finished_at BIGINT NULL,
            paused_at BIGINT NULL,
            cancelled_at BIGINT NULL
        );

        CREATE UNIQUE INDEX chapter_revision_sweep_session_active_idx ON chapterrevisionsweepsession (active_marker);
        -- the worker claims the oldest runnable session
        CREATE INDEX chapter_revision_sweep_session_claim_idx ON chapterrevisionsweepsession (state, next_item_at, id);

        CREATE TABLE IF NOT EXISTS chapterrevisionsweepitem (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session INT NOT NULL,
            -- immutable snapshots, not references: the audit outlives the rows it describes
            manga_id INT NULL,
            chapter_id INT NULL,
            source_id BIGINT NULL,
            -- the chapter identity the candidate has to be created under
            chapter_key VARCHAR(64) NOT NULL,
            series_title VARCHAR(512) NOT NULL,
            chapter_name VARCHAR(512) NOT NULL,
            source_chapter_url VARCHAR(2048) NOT NULL,
            -- the acquisition policy resolved for this item when the session started
            policy VARCHAR(64) NOT NULL,
            state VARCHAR(64) NOT NULL DEFAULT '${ChapterRevisionSweepItemState.PENDING.name}',
            attempts INT NOT NULL DEFAULT 0,
            last_error VARCHAR(1024) NULL,
            candidate_count INT NULL,
            -- earliest instant this item may be retried, null while it is due immediately
            due_at BIGINT NULL,
            started_at BIGINT NULL,
            finished_at BIGINT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT FK_CHAPTERREVISIONSWEEPITEM_SESSION__ID
                FOREIGN KEY (session) REFERENCES chapterrevisionsweepsession(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT
        );

        -- the worker claims the earliest claimable item of one session, ordered by its own due time
        CREATE INDEX chapter_revision_sweep_item_backlog_idx ON chapterrevisionsweepitem (session, state, due_at, id);
        -- the per-session item listing is ordered by id and filtered only by session
        CREATE INDEX chapter_revision_sweep_item_session_idx ON chapterrevisionsweepitem (session, id);

        -- exactly one persisted schedule row; the check makes a second one impossible in the
        -- database rather than in the code that inserts it
        CREATE TABLE IF NOT EXISTS chapterrevisionsweepschedule (
            id INT NOT NULL PRIMARY KEY,
            -- when the next automatic sweep is due; always a future instant when a run completed
            next_due_at BIGINT NOT NULL,
            last_run_at BIGINT NULL,
            last_session_id INT NULL,
            -- earliest instant a scheduled occurrence that could not be started may be retried; null
            -- while no retry is pending. `next_due_at` deliberately stays where it is, so a backoff
            -- defers when the occurrence is retried without ever consuming or skipping it.
            retry_not_before BIGINT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT CHK_CHAPTERREVISIONSWEEPSCHEDULE_SINGLETON CHECK (id = 1)
        );

        -- the independent content-comparison dimension of a revision
        --
        -- The default is NOT_EVALUATED, not PENDING: a row that already existed when this migration
        -- runs was never compared, and `ADD COLUMN ... NOT NULL DEFAULT` hands it that value in both
        -- dialects. PENDING means a comparison is still owed, which is only ever true of a candidate
        -- recorded after the dimension existed, and every creation path writes it explicitly.
        ALTER TABLE chapterrevision ADD COLUMN comparison_state VARCHAR(64) NOT NULL DEFAULT '${ChapterRevisionComparisonState.NOT_EVALUATED.name}';
        ALTER TABLE chapterrevision ADD COLUMN comparison_baseline_revision INT NULL;
        ALTER TABLE chapterrevision ADD COLUMN compared_at BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN comparison_error VARCHAR(1024) NULL;
        -- when the staged pages of an EXACT_MATCH revision may be removed; null while unscheduled
        ALTER TABLE chapterrevision ADD COLUMN comparison_cleanup_due_at BIGINT NULL;

        -- the exactly-one-candidate binding of a sweep item; null for every other discovery
        ALTER TABLE chapterrevision ADD COLUMN sweep_item INT NULL;

        CREATE UNIQUE INDEX chapter_revision_sweep_item_idx ON chapterrevision (sweep_item);
        -- the comparison audit is browsed per state, and a baseline that is pruned must null the
        -- reference instead of deleting the comparison that used it
        CREATE INDEX chapter_revision_comparison_state_idx ON chapterrevision (comparison_state, id);
        -- the cleanup backlog is claimed by its persisted due time
        CREATE INDEX chapter_revision_comparison_cleanup_idx ON chapterrevision (comparison_cleanup_due_at, id);
        ALTER TABLE chapterrevision ADD CONSTRAINT FK_CHAPTERREVISION_COMPARISONBASELINE__ID
            FOREIGN KEY (comparison_baseline_revision) REFERENCES chapterrevision(ID)
            ON DELETE SET NULL ON UPDATE RESTRICT;
        ALTER TABLE chapterrevision ADD CONSTRAINT FK_CHAPTERREVISION_SWEEPITEM__ID
            FOREIGN KEY (sweep_item) REFERENCES chapterrevisionsweepitem(ID)
            ON DELETE SET NULL ON UPDATE RESTRICT;
        """.trimIndent()
}
