package suwayomi.tachidesk.server.database.migration

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import de.neonew.exposed.migrations.helpers.SQLMigration
import suwayomi.tachidesk.manga.model.dataclass.CanonicalBindingRole
import suwayomi.tachidesk.manga.model.dataclass.CanonicalDuplicateStrategy

// Adds the canonical identity control plane: an archive-level work several source manga bindings may
// belong to, plus the policy that is *recorded* for resolving duplicates between them.
//
// This migration is additive on purpose. It does not touch `manga`, `chapter` or the archive: a
// canonical binding is a claim about which source rows describe the same series, not a rewrite of
// them, so a manga that nobody has bound keeps behaving exactly as it did before this table existed.
// Nothing is backfilled - a database without works simply has none.
//
// `canonicalwork.work_key` is the public identity and is opaque, so it is a random value rather than
// anything derived from a mutable title. `duplicate_strategy` defaults to KEEP_ALL: the conservative
// value, and the only one that changes nothing until an operator chooses otherwise.
//
// `canonicalsourcebinding` carries two invariants as indexes rather than as conventions:
//
//   * `unique (manga)` - one manga belongs to at most one work. Nulls are distinct in both dialects,
//     so a binding whose manga was deleted keeps its audit without blocking a later re-bind.
//   * `unique (primary_marker)` - at most one primary per work. The marker holds the work id while a
//     row is primary and is null otherwise, which scopes the uniqueness to the work and makes
//     "two primaries" impossible even for two concurrent writes.
//
//   * `unique (work, priority)` makes the ordering of a work's bindings a permutation, so "the next
//     fallback" is never ambiguous.
//
// The manga reference is SET NULL and the snapshot columns beside it (title, url, source id and
// name) are never rewritten: deleting a manga must not erase what a work contained, and it must
// never delete the work, the archive or any revision history.
//
// The four `chapterrevision` columns are a per-candidate snapshot of the binding a discovery was
// made under. They are plain nullable columns rather than a foreign key precisely because the
// snapshot must survive the deletion of the work it names - a revision archived under a work stays
// intelligible after that work is gone. No backfill runs, so a revision that predates canonical
// identity decodes as unbound, which is what it was.
@Suppress("ClassName", "unused")
class M0078_CanonicalIdentity : SQLMigration() {
    // language=sql
    override val sql: String =
        """
        CREATE TABLE IF NOT EXISTS canonicalwork (
            -- identity syntax both H2 and PostgreSQL accept
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            -- opaque public identity; random, never derived from a title or a source URL
            work_key VARCHAR(64) NOT NULL,
            title VARCHAR(512) NOT NULL,
            duplicate_strategy VARCHAR(64) NOT NULL DEFAULT '${CanonicalDuplicateStrategy.KEEP_ALL.name}',
            preferred_scanlator VARCHAR(256) NULL,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL
        );

        -- the work key is what the API and the export address a work by, so it is the lookup key
        CREATE UNIQUE INDEX canonical_work_key_idx ON canonicalwork (work_key);
        -- works are listed ordered by id by default, or by title when asked
        CREATE INDEX canonical_work_title_idx ON canonicalwork (title, id);
        CREATE INDEX canonical_work_updated_idx ON canonicalwork (updated_at, id);

        CREATE TABLE IF NOT EXISTS canonicalsourcebinding (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            work INT NOT NULL,
            -- null once the source manga is deleted; the snapshot columns below survive it
            manga INT NULL,
            role VARCHAR(64) NOT NULL DEFAULT '${CanonicalBindingRole.ACTIVE.name}',
            priority INT NOT NULL DEFAULT 0,
            -- holds the work id while this row is the work's primary, null otherwise
            primary_marker VARCHAR(64) NULL,
            -- immutable audit snapshot of the manga at bind time
            manga_title VARCHAR(512) NULL,
            manga_url VARCHAR(2048) NULL,
            source_id BIGINT NULL,
            source_name VARCHAR(256) NULL,
            bound_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT FK_CANONICALSOURCEBINDING_WORK__ID
                FOREIGN KEY (work) REFERENCES canonicalwork(ID)
                ON DELETE CASCADE ON UPDATE RESTRICT,
            CONSTRAINT FK_CANONICALSOURCEBINDING_MANGA__ID
                FOREIGN KEY (manga) REFERENCES manga(ID)
                ON DELETE SET NULL ON UPDATE RESTRICT
        );

        -- one manga belongs to at most one work; nulls are distinct in both dialects
        CREATE UNIQUE INDEX canonical_binding_manga_idx ON canonicalsourcebinding (manga);
        -- at most one primary per work, enforced by the work-scoped marker
        CREATE UNIQUE INDEX canonical_binding_primary_idx ON canonicalsourcebinding (primary_marker);
        -- the ordering within a work is a permutation: no two bindings share a place
        CREATE UNIQUE INDEX canonical_binding_priority_idx ON canonicalsourcebinding (work, priority);
        -- bindings are always listed for one work, ordered by priority then id
        CREATE INDEX canonical_binding_work_idx ON canonicalsourcebinding (work, priority, id);

        -- per-candidate snapshot of the canonical binding a discovery was made under.
        --
        -- Deliberately not a foreign key: the snapshot has to stay readable after the work it names
        -- is deleted, and a revision that predates canonical identity stays null.
        ALTER TABLE chapterrevision ADD COLUMN canonical_work_key VARCHAR(64) NULL;
        ALTER TABLE chapterrevision ADD COLUMN canonical_binding_role VARCHAR(64) NULL;
        ALTER TABLE chapterrevision ADD COLUMN canonical_binding_priority INT NULL;
        ALTER TABLE chapterrevision ADD COLUMN canonical_binding_primary BOOLEAN NULL;
        ALTER TABLE chapterrevision ADD COLUMN canonical_binding_source_id BIGINT NULL;
        ALTER TABLE chapterrevision ADD COLUMN canonical_binding_manga_url VARCHAR(2048) NULL;

        -- "which revisions were discovered under this work" is the audit query the snapshot exists for
        CREATE INDEX chapter_revision_canonical_work_idx ON chapterrevision (canonical_work_key, id);
        """.trimIndent()
}
