package suwayomi.tachidesk.manga.impl

/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

/**
 * The largest difference tolerated between this server's clock and the object store's.
 *
 * A signed location is generated by the remote and read here, so the two clocks are different clocks.
 * The tolerance loosens the rejection of a location that has just expired and of one whose signature
 * time is slightly ahead, and it never lengthens the validity of an accepted location.
 */
private const val CLOCK_SKEW_SECONDS = 300L

/**
 * How much longer than the requested lifetime a remote may report before its answer is refused.
 *
 * A backend is allowed to round the requested duration up; anything beyond rounding means the location
 * is not bounded by the lifetime this server asked for, which is exactly what has to be proven.
 */
private const val LIFETIME_TOLERANCE_SECONDS = 60L

/** Earliest absolute time a signature may carry and still be believed. 2000-01-01T00:00:00Z. */
private const val MIN_PLAUSIBLE_EPOCH_SECOND = 946_684_800L

/** Latest absolute time a signature may carry and still be believed. 2100-01-01T00:00:00Z. */
private const val MAX_PLAUSIBLE_EPOCH_SECOND = 4_102_444_800L

/**
 * Proves that one generated direct-delivery location is bounded in time.
 *
 * `rclone link --expire` is a request, not a guarantee: the rclone documentation states that a backend
 * which does not support expiry ignores the flag and answers with a link that never expires. A
 * location that is handed to a client is a bearer credential for the payload, so "short-lived" may not
 * rest on the flag alone. This object therefore reads the signed query the backend itself produced and
 * accepts it only when that query states a bounded validity for a signing family whose expiry
 * parameters are meaningful.
 *
 * Only the three families whose query carries both the signature and its own expiry are recognized:
 * AWS/R2/S3 (`X-Amz-Date` + `X-Amz-Expires` + `X-Amz-Signature`), Google (`X-Goog-Date` +
 * `X-Goog-Expires` + `X-Goog-Signature`) and Azure SAS (`se` + `sig`). A location from any other
 * backend cannot be verified here, and it is refused rather than trusted - an operator who knows their
 * backend does bound the link can opt out of this check explicitly.
 *
 * Nothing about the location is ever logged, returned or stored: the only output of this object is a
 * boolean.
 */
internal object ArchiveSignedUrlExpiry {
    /**
     * True when [location] proves its own bounded expiry within [requestedLifetimeSeconds] of [now].
     *
     * The location itself stays the value it is: this only decides whether it may be redirected to.
     */
    fun provesBoundedExpiry(
        location: String,
        requestedLifetimeSeconds: Long,
        now: Long,
    ): Boolean {
        val url = location.toHttpUrlOrNull() ?: return false

        // A parameter this check interprets must be unambiguous: a name that appears more than once, in
        // any casing, could mean one value to the backend and another to whoever reads it next. Values
        // are collected per lowercased name so `X-Amz-Expires` and `x-amz-expires` cannot both be read.
        val parameters = HashMap<String, MutableList<String>>()
        url.queryParameterNames.forEach { name ->
            parameters.getOrPut(name.lowercase()) { mutableListOf() } +=
                url.queryParameterValues(name).filterNotNull()
        }

        val lifetimes = requestedLifetimeSeconds.coerceAtLeast(0)

        // A location belongs to exactly one signing family. A query carrying two of them at once is
        // refused rather than resolved by preference, because nothing here can tell which family the
        // backend meant and reading the wrong one would verify a different link than the one served.
        val families =
            listOf(
                AWS_MARKERS.any { it in parameters },
                GOOGLE_MARKERS.any { it in parameters },
                // `sig` alone is too generic to identify a family, so Azure is only counted with its
                // signed expiry present as well
                AZURE_MARKERS.all { it in parameters },
            ).count { it }
        if (families != 1) return false

        return when {
            AWS_MARKERS.any { it in parameters } -> awsOrGoogle(parameters, AWS_KEYS, lifetimes, now)
            GOOGLE_MARKERS.any { it in parameters } -> awsOrGoogle(parameters, GOOGLE_KEYS, lifetimes, now)
            else -> azureSas(parameters, lifetimes, now)
        }
    }

    /**
     * AWS/R2/S3 and Google carry the same three parameters under their own prefixes.
     *
     * A family is recognized by any of its markers, so a link that names only the signature is routed
     * here and refused for the missing expiry instead of silently falling through to `false`.
     */
    private fun awsOrGoogle(
        parameters: Map<String, List<String>>,
        keys: SigningKeys,
        requestedLifetimeSeconds: Long,
        now: Long,
    ): Boolean {
        val date = single(parameters, keys.date) ?: return false
        val expires = single(parameters, keys.expires) ?: return false
        if (single(parameters, keys.signature) == null) return false

        val issuedAt = parseBasicDate(date) ?: return false
        val lifetime = parsePositiveSeconds(expires) ?: return false

        return boundedExpiry(
            issuedAtEpochSecond = issuedAt,
            lifetimeSeconds = lifetime,
            requestedLifetimeSeconds = requestedLifetimeSeconds,
            now = now,
        )
    }

    /** Azure SAS states one absolute expiry, so the bounded validity is the distance to it. */
    private fun azureSas(
        parameters: Map<String, List<String>>,
        requestedLifetimeSeconds: Long,
        now: Long,
    ): Boolean {
        val expiry = single(parameters, "se") ?: return false
        if (single(parameters, "sig") == null) return false

        val expiresAt = parseAbsoluteTime(expiry) ?: return false
        if (expiresAt !in MIN_PLAUSIBLE_EPOCH_SECOND..MAX_PLAUSIBLE_EPOCH_SECOND) return false
        if (expiresAt < now - CLOCK_SKEW_SECONDS) return false

        return expiresAt <= now + requestedLifetimeSeconds + LIFETIME_TOLERANCE_SECONDS
    }

    /**
     * The shape every bounded validity has to satisfy.
     *
     * [lifetimeSeconds] is what the backend reported, which is what has to be within what was asked for;
     * [issuedAtEpochSecond] is when the backend signed the location, which has to be a believable instant
     * that is not in the future.
     */
    private fun boundedExpiry(
        issuedAtEpochSecond: Long,
        lifetimeSeconds: Long,
        requestedLifetimeSeconds: Long,
        now: Long,
    ): Boolean {
        if (issuedAtEpochSecond !in MIN_PLAUSIBLE_EPOCH_SECOND..MAX_PLAUSIBLE_EPOCH_SECOND) return false
        if (issuedAtEpochSecond > now + CLOCK_SKEW_SECONDS) return false
        if (lifetimeSeconds <= 0) return false
        if (lifetimeSeconds > requestedLifetimeSeconds + LIFETIME_TOLERANCE_SECONDS) return false
        // a lifetime that cannot be added without leaving the believable window is not a validity
        if (lifetimeSeconds > MAX_PLAUSIBLE_EPOCH_SECOND - issuedAtEpochSecond) return false

        val expiresAt = issuedAtEpochSecond + lifetimeSeconds
        // a location that has already expired is not a way to fetch anything, so accepting it would
        // turn a verification into a redirect to a dead link
        return expiresAt >= now - CLOCK_SKEW_SECONDS
    }

    /**
     * One unambiguous value of a recognized parameter, or null.
     *
     * A value has to appear exactly once and carry no whitespace at all: a parameter that is padded, that
     * decodes to an empty value, or that appears in two casings is not one value this check can read, and
     * a query that spells it two ways is exactly the ambiguity that must not be resolved by guessing.
     */
    private fun single(
        parameters: Map<String, List<String>>,
        name: String,
    ): String? {
        val values = parameters[name.lowercase()] ?: return null
        if (values.size != 1) return null

        val value = values.single()
        if (value.isEmpty() || value.any { it.isWhitespace() }) return null
        return value
    }

    /** `20260101T000000Z`, `20260101T000000123Z` or `20260101`, read as UTC. */
    private fun parseBasicDate(value: String): Long? {
        BASIC_DATE_TIME
            .mapNotNull { format -> runCatching { LocalDateTime.parse(value, format) }.getOrNull() }
            .firstOrNull()
            ?.let { return it.toInstant(ZoneOffset.UTC).epochSecond }

        return runCatching { LocalDate.parse(value, BASIC_DATE) }
            .getOrNull()
            ?.atStartOfDay(ZoneOffset.UTC)
            ?.toInstant()
            ?.epochSecond
    }

    /** A whole, positive number of seconds, refused rather than clamped when it is not one. */
    private fun parsePositiveSeconds(value: String): Long? {
        if (value.any { it !in '0'..'9' }) return null
        val seconds = value.toLongOrNull() ?: return null
        return seconds.takeIf { it > 0 }
    }

    /**
     * An absolute time as the signing families spell it.
     *
     * Azure states an offset time, but an offset-less value is read as UTC rather than refused: it can
     * only come from a backend whose own convention is UTC, and treating a missing offset as unknown
     * would refuse a link that is provably bounded. Anything unparseable stays refused.
     */
    private fun parseAbsoluteTime(value: String): Long? {
        runCatching { OffsetDateTime.parse(value, DateTimeFormatter.ISO_OFFSET_DATE_TIME) }
            .getOrNull()
            ?.let { return it.toInstant().epochSecond }

        runCatching { Instant.parse(value) }
            .getOrNull()
            ?.let { return it.epochSecond }

        return runCatching { LocalDateTime.parse(value, DateTimeFormatter.ISO_LOCAL_DATE_TIME) }
            .getOrNull()
            ?.toInstant(ZoneOffset.UTC)
            ?.epochSecond
    }

    /** The three parameters one signing family states its algorithm with. */
    private class SigningKeys(
        val date: String,
        val expires: String,
        val signature: String,
    )

    private val AWS_KEYS = SigningKeys("x-amz-date", "x-amz-expires", "x-amz-signature")
    private val GOOGLE_KEYS = SigningKeys("x-goog-date", "x-goog-expires", "x-goog-signature")

    /** Any of a family's parameters identifies it, so a partial answer is refused, never ignored. */
    private val AWS_MARKERS = listOf(AWS_KEYS.date, AWS_KEYS.expires, AWS_KEYS.signature)
    private val GOOGLE_MARKERS = listOf(GOOGLE_KEYS.date, GOOGLE_KEYS.expires, GOOGLE_KEYS.signature)
    private val AZURE_MARKERS = listOf("se", "sig")

    private val BASIC_DATE_TIME =
        listOf(
            DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss'Z'"),
            DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmssSSS'Z'"),
        )

    private val BASIC_DATE = DateTimeFormatter.ofPattern("yyyyMMdd")
}
